In [1]:
import os
from pathlib import Path

import numpy as np
import pandas as pd

from io import StringIO

## Table S8. 2D automated marker gene discovery: section-level feature correlations

In [23]:
datas = []
for dtype in ['visiumhd', 'xenium', 'cosmx']:
    output_dir = Path(f'../data/spatial/regions/{dtype}')
    for rtype in ['regions', 'tme']:
        corrs = pd.read_csv(output_dir / f'correlations_{rtype}.txt', sep='\t', index_col=0)
        corrs['region_type'] = rtype
        corrs['data_type'] = dtype
        corrs['test_type'] = 'spearman'
        corrs['section_id'] = corrs.index.to_list()
        datas.append(corrs)
corr_df = pd.concat(datas)
corr_df

,SAMD11,NOC2L,KLHL17,PLEKHN1,PERM1,HES4,ISG15,AGRN,RNF223,C1orf159,...,PRSS2,RPL21,RPL22,RPL32,RPL34,RPL37,RPS4Y1,SAA1/2,TPSAB1/B2,TPT1
sid,,,,,,,,,,,,,,,,,,,,,
HT935Z1-S1H1Fp1U1,0.054850,0.094992,0.159265,0.089509,0.146228,0.038131,0.051272,-0.025287,-0.024582,0.198463,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
HT891Z1-S2H3Fp1U2,0.099561,-0.021334,0.056442,0.089045,-0.025795,-0.060334,-0.031830,0.179327,0.045123,0.030039,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
HT704B1-S1H3Fp1U2,-0.012116,-0.117529,-0.104471,-0.028525,0.025600,0.063775,-0.098679,0.035609,0.020965,-0.056376,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
HT891Z1-S2H3Fp1U33,0.142193,-0.067160,0.008162,0.016771,-0.034001,-0.036685,0.025559,0.212697,0.094422,0.021616,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
HT727B1-S1H4Fp1U1,0.096576,0.152678,0.185385,0.235758,0.058075,0.093136,0.152405,0.146968,0.091593,0.103641,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
HT704B1-S1H3Fp1_U14,NaN,NaN,NaN,NaN,NaN,NaN,0.097462,NaN,NaN,NaN,...,0.142985,0.167877,0.178185,0.185898,0.216422,0.231400,0.129857,0.207028,0.113490,0.157853
HT997Z1-S1H1FP1U1,NaN,NaN,NaN,NaN,NaN,0.049023,0.050542,0.039277,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
HT891Z1-S2H3FP1U60,NaN,NaN,NaN,NaN,NaN,0.027304,0.033034,0.028398,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
HT704B1-S1H3Fp1_U47,NaN,NaN,NaN,NaN,NaN,NaN,0.052506,NaN,NaN,NaN,...,0.082850,0.096649,0.139538,0.106911,0.159643,0.142746,0.085766,0.156627,0.065017,0.119804
HT935Z1-S1H1FP1U2,NaN,NaN,NaN,NaN,NaN,0.072072,0.060928,0.050787,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
output_dir = Path(f'../data/spatial/regions/visium')
datas = []
for disease in ['breast', 'prostate']:
    vals = pd.read_csv(output_dir / f'ttest_stat_sectionlevel_{disease}.txt', sep='\t', index_col=0)
    vals['section_id'] = vals.index.to_list()
    datas.append(vals)
ttest_df = pd.concat(datas)
ttest_df['region_type'] = 'regions'
ttest_df['data_type'] = 'visium'
ttest_df['test_type'] = 'ttest'
ttest_df

,SAMD11,NOC2L,KLHL17,PLEKHN1,PERM1,HES4,ISG15,AGRN,C1orf159,TTLL10,...,RNASE11,KRTAP3-1,KRTAP10-6,KRTAP12-4,BMP15,TBX22,section_id,region_type,data_type,test_type
sid,,,,,,,,,,,,,,,,,,,,,
HT308B1-S1H5Fc2U1Z1Bs1,-1.564976,-1.840577,-1.147339,0.383632,-1.826827,1.130172,-1.811070,0.893158,-1.278152,-0.664927,...,NaN,NaN,NaN,NaN,NaN,NaN,HT308B1-S1H5Fc2U1Z1Bs1,regions,visium,ttest
HT297B1-S1H1Fc2U1Z1Bs1,-2.028694,0.687056,-2.772928,1.323669,-0.192274,0.539072,-1.464357,0.001781,-2.859639,-1.997037,...,NaN,NaN,NaN,NaN,NaN,NaN,HT297B1-S1H1Fc2U1Z1Bs1,regions,visium,ttest
HT308B1-S1H4Fc2U1Z1Bs1,0.809473,0.905881,1.671769,-1.810450,0.513257,-0.788304,0.272030,-0.627286,0.569280,0.839011,...,NaN,NaN,NaN,NaN,NaN,NaN,HT308B1-S1H4Fc2U1Z1Bs1,regions,visium,ttest
HT206B1-S1Fc1U1Z1B1,0.021816,-1.958272,-1.542669,-0.554473,1.000000,-1.579021,-1.573082,0.396833,-2.144108,-1.110437,...,NaN,NaN,NaN,NaN,NaN,NaN,HT206B1-S1Fc1U1Z1B1,regions,visium,ttest
HT206B1-S1Fc1U4Z1B1,-0.161510,0.478249,1.038886,-0.877248,1.000000,-1.135881,-0.414375,-1.074514,-0.774918,-1.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,HT206B1-S1Fc1U4Z1B1,regions,visium,ttest
HT308B1-S1H1Fc2U1Z1Bs1,2.296807,-0.314274,0.295140,0.357478,2.249641,0.539731,-1.838353,1.364151,0.160514,1.450001,...,NaN,NaN,NaN,NaN,NaN,NaN,HT308B1-S1H1Fc2U1Z1Bs1,regions,visium,ttest
HT480B1-S1H1Fs1U2Bp1,-0.410397,0.253624,-0.858671,0.675085,1.000000,-2.032925,0.046243,0.311807,-1.299142,-2.032050,...,NaN,NaN,NaN,NaN,NaN,NaN,HT480B1-S1H1Fs1U2Bp1,regions,visium,ttest
HT206B1-S1Fc1U3Z1B1,-0.435607,0.751064,-0.052750,0.276920,1.000000,-0.632850,-0.933748,-1.707799,-1.023137,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,HT206B1-S1Fc1U3Z1B1,regions,visium,ttest
HT397B1-S1H2Fs4U1Bp1,0.561408,0.687081,0.502713,-0.729037,NaN,1.078320,3.271862,1.892495,0.168377,1.439624,...,NaN,NaN,NaN,NaN,NaN,NaN,HT397B1-S1H2Fs4U1Bp1,regions,visium,ttest
HT206B1-S1Fc1U5Z1B1,0.229615,1.117154,0.872430,-0.928378,-1.000000,-1.107078,-0.587998,-1.654178,0.847170,-1.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,HT206B1-S1Fc1U5Z1B1,regions,visium,ttest
HT480B1-S1H3Fs1U1Bp1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,HT480B1-S1H3Fs1U1Bp1,regions,visium,ttest
HT486B1-S1H1Fs1U1Bp1,NaN,1.567883,0.759359,0.912318,NaN,1.672824,-1.371531,1.373717,-0.298611,1.465062,...,NaN,NaN,NaN,NaN,NaN,NaN,HT486B1-S1H1Fs1U1Bp1,regions,visium,ttest
HT397B1-S1H3Fs1U1Bp1,-1.731543,-0.138769,0.799913,-1.829915,NaN,0.010778,2.529454,1.559255,0.313044,2.944274,...,NaN,NaN,NaN,NaN,NaN,NaN,HT397B1-S1H3Fs1U1Bp1,regions,visium,ttest
HT206B1-S1Fc1U2Z1B1,0.710318,0.339572,-0.563136,0.701400,NaN,-0.623785,-0.158511,-1.934917,0.282960,-1.087722,...,NaN,NaN,NaN,NaN,NaN,NaN,HT206B1-S1Fc1U2Z1B1,regions,visium,ttest
HT323B1-S1H1Fc2U1Z1Bs1,-0.519143,0.524308,0.734819,1.690390,0.356473,-0.525549,-2.303670,0.381343,1.417130,1.549534,...,NaN,NaN,NaN,NaN,NaN,NaN,HT323B1-S1H1Fc2U1Z1Bs1,regions,visium,ttest
HT397B1-S1H3A1U1Bp1,0.350140,-0.482680,0.798205,-0.971618,NaN,-1.189359,-0.838887,0.725727,0.798763,2.614706,...,NaN,NaN,NaN,NaN,NaN,NaN,HT397B1-S1H3A1U1Bp1,regions,visium,ttest
HT397B1-S1H3A1U21Bp1,-0.116651,-0.321933,-0.468957,-2.324383,NaN,0.715321,-1.285654,0.010205,-0.276240,0.724957,...,NaN,NaN,NaN,NaN,NaN,NaN,HT397B1-S1H3A1U21Bp1,regions,visium,ttest
HT480B1-S1H1Fs1U1Bp1,-2.179930,-1.211503,0.755991,1.356200,NaN,-2.252821,-1.133255,0.593206,-1.395975,-0.317083,...,NaN,NaN,NaN,NaN,NaN,NaN,HT480B1-S1H1Fs1U1Bp1,regions,visium,ttest
SP060Z1-Fp1U1Bp1,-1.000000,-0.574539,NaN,-1.309172,NaN,-0.294579,0.174354,-5.974367,-1.274838,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,SP060Z1-Fp1U1Bp1,regions,visium,ttest
SP017Z1-Fp1B27Us1,0.265336,-1.822604,0.944240,0.867068,NaN,-0.908182,2.197151,0.488232,-0.420545,-1.625947,...,NaN,NaN,NaN,NaN,NaN,NaN,SP017Z1-Fp1B27Us1,regions,visium,ttest

In [26]:
merged = pd.concat((corr_df, ttest_df))
merged = merged.melt(id_vars=['section_id', 'region_type', 'data_type', 'test_type'])
merged

,section_id,region_type,data_type,test_type,variable,value
0,HT935Z1-S1H1Fp1U1,regions,visiumhd,spearman,SAMD11,0.054850
1,HT891Z1-S2H3Fp1U2,regions,visiumhd,spearman,SAMD11,0.099561
2,HT704B1-S1H3Fp1U2,regions,visiumhd,spearman,SAMD11,-0.012116
3,HT891Z1-S2H3Fp1U33,regions,visiumhd,spearman,SAMD11,0.142193
4,HT727B1-S1H4Fp1U1,regions,visiumhd,spearman,SAMD11,0.096576
...,...,...,...,...,...,...
6724291,HT397B1-S1H3A1U1Bp1,regions,visium,ttest,KRTAP10-6,NaN
6724292,HT397B1-S1H3A1U21Bp1,regions,visium,ttest,KRTAP10-6,NaN
6724293,HT480B1-S1H1Fs1U1Bp1,regions,visium,ttest,KRTAP10-6,NaN
6724294,SP060Z1-Fp1U1Bp1,regions,visium,ttest,KRTAP10-6,NaN
6724295,SP017Z1-Fp1B27Us1,regions,visium,ttest,KRTAP10-6,NaN

In [30]:
merged.to_csv('../data/spatial/supplemental/supptable8_feature_metrics.txt.gz', sep='\t', index=False)

## Table S9. 2D marker gene discovery: visium  barcode annotations

In [31]:
annots = pd.read_csv('../data/spatial/annotations/visium/all_annotations.txt', sep='\t', index_col=0)
annots

,sid,Barcode,label
id,,,
HT308B1-S1H4Fc2U1Z1Bs1_AAACCTAAGCAGCCGG-1,HT308B1-S1H4Fc2U1Z1Bs1,AAACCTAAGCAGCCGG-1,IDC 4
HT308B1-S1H4Fc2U1Z1Bs1_AAACGAAGAACATACC-1,HT308B1-S1H4Fc2U1Z1Bs1,AAACGAAGAACATACC-1,DCIS 15
HT308B1-S1H4Fc2U1Z1Bs1_AAATGCTCGTTACGTT-1,HT308B1-S1H4Fc2U1Z1Bs1,AAATGCTCGTTACGTT-1,IDC 7
HT308B1-S1H4Fc2U1Z1Bs1_AAATTAACGGGTAGCT-1,HT308B1-S1H4Fc2U1Z1Bs1,AAATTAACGGGTAGCT-1,IDC 8
HT308B1-S1H4Fc2U1Z1Bs1_AAATTGCGGCGGTTCT-1,HT308B1-S1H4Fc2U1Z1Bs1,AAATTGCGGCGGTTCT-1,IDC 7
...,...,...,...
HT397B1-S1H3A1U1Bp1_TTGGACCTATAACAGT-1,HT397B1-S1H3A1U1Bp1,TTGGACCTATAACAGT-1,IDC 3
HT397B1-S1H3A1U1Bp1_TTGGGACGTAAGAGTT-1,HT397B1-S1H3A1U1Bp1,TTGGGACGTAAGAGTT-1,IDC 4
HT397B1-S1H3A1U1Bp1_TTGTCGTTCAGTTACC-1,HT397B1-S1H3A1U1Bp1,TTGTCGTTCAGTTACC-1,DCIS 3
HT397B1-S1H3A1U1Bp1_TTGTGGTAGGAGGGAT-1,HT397B1-S1H3A1U1Bp1,TTGTGGTAGGAGGGAT-1,DCIS 1
HT397B1-S1H3A1U1Bp1_TTGTGTATGCCACCAA-1,HT397B1-S1H3A1U1Bp1,TTGTGTATGCCACCAA-1,IDC 1

In [32]:
annots.to_csv('../data/spatial/supplemental/supptable9_visium_barcodes.txt.gz', sep='\t', index=False)

## Table S10. scRNA-seq luminal vs. basal DEGs

In [36]:
datas = []
for disease in ['breast', 'prostate']:
    sc_degs = pd.read_csv(f'../data/single-cell/degs/{disease}.txt', sep='\t', index_col=0)
    sc_degs.insert(0, 'disease', disease)
    sc_degs['gene'] = sc_degs.index
    datas.append(sc_degs)
sc_degs = pd.concat(datas)
sc_degs = sc_degs[['disease', 'gene', 'scores', 'logfoldchanges']]
sc_degs

           disease      gene      scores  logfoldchanges
names
DMD         breast       DMD   84.589120        4.839778
CALD1       breast     CALD1   79.198660        4.038258
DST         breast       DST   73.885810        3.369953
RBMS3       breast     RBMS3   71.332375        4.024954
MIR205HG    breast  MIR205HG   70.113760        3.999832
...            ...       ...         ...             ...
TMPRSS2   prostate   TMPRSS2 -106.596954       -4.108202
AFF3      prostate      AFF3 -112.303260       -5.140292
CPNE4     prostate     CPNE4 -112.510956       -5.191433
KLK2      prostate      KLK2 -113.057110       -4.934494
KLK3      prostate      KLK3 -113.811970       -4.955718

[65019 rows x 4 columns]

In [37]:
sc_degs.to_csv('../data/spatial/supplemental/supptable10_scdegs.txt.gz', sep='\t', index=False)

## sample mapping

In [7]:
meta_3d = pd.read_csv(StringIO("""case	section_id	z_depth (microns)	data_type	cohort	disease
HT206B1	HT206B1-U1	0	xenium	3d	breast
HT206B1	HT206B1-U4	5	he	3d	breast
HT206B1	HT206B1-U2	15	codex	3d	breast
HT206B1	HT206B1-U5	20	codex	3d	breast
HT206B1	HT206B1-U8	40	xenium	3d	breast
HT206B1	HT206B1-U9	45	xenium	3d	breast
HT206B1	HT206B1-U10	50	codex	3d	breast
HT206B1	HT206B1-U12	60	he	3d	breast
HT206B1	HT206B1-U13	65	codex	3d	breast
HT206B1	HT206B1-U15	75	cosmx	3d	breast
HT206B1	HT206B1-U16	80	xenium	3d	breast
HT206B1	HT206B1-U17	85	xenium	3d	breast
HT206B1	HT206B1-U18	90	codex	3d	breast
HT206B1	HT206B1-U20	100	he	3d	breast
HT206B1	HT206B1-U21	105	codex	3d	breast
HT206B1	HT206B1-U24	120	xenium	3d	breast
HT339B2	HT339B2-H1-U1	0	visium	3d	breast
HT339B2	HT339B2-H1-U2	5	codex	3d	breast
HT397B1	HT397B1-U1	0	visium	3d	breast
HT397B1	HT397B1-U2	5	codex	3d	breast
HT397B1	HT397B1-U4	15	he	3d	breast
HT397B1	HT397B1-U8	35	he	3d	breast
HT397B1	HT397B1-U11	50	he	3d	breast
HT397B1	HT397B1-U12	55	codex	3d	breast
HT397B1	HT397B1-U16	75	he	3d	breast
HT397B1	HT397B1-U21	100	visium	3d	breast
HT397B1	HT397B1-U22	105	codex	3d	breast
HT397B1	HT397B1-U20	125	he	3d	breast
HT397B1	HT397B1-U28	145	he	3d	breast
HT397B1	HT397B1-U31	150	codex	3d	breast
HT565B1	HT565B1-H2-U1	0	visium	3d	breast
HT565B1	HT565B1-H2-U2	5	codex	3d	breast
HT704B1	HT704B1-U1	0	xenium	3d	breast
HT704B1	HT704B1-U2	5	visiumhd	3d	breast
HT704B1	HT704B1-U11	50	codex	3d	breast
HT704B1	HT704B1-U12	55	he	3d	breast
HT704B1	HT704B1-U14	65	cosmx	3d	breast
HT704B1	HT704B1-U15	70	he	3d	breast
HT704B1	HT704B1-U17	80	xenium	3d	breast
HT704B1	HT704B1-U19	90	codex	3d	breast
HT704B1	HT704B1-U20	95	he	3d	breast
HT704B1	HT704B1-U22	105	cosmx	3d	breast
HT704B1	HT704B1-U23	110	he	3d	breast
HT704B1	HT704B1-U26	125	xenium	3d	breast
HT704B1	HT704B1-U27	130	codex	3d	breast
HT704B1	HT704B1-U28	135	he	3d	breast
HT704B1	HT704B1-U31	150	he	3d	breast
HT704B1	HT704B1-U33	160	xenium	3d	breast
HT704B1	HT704B1-U35	170	codex	3d	breast
HT704B1	HT704B1-U36	175	he	3d	breast
HT704B1	HT704B1-U39	190	he	3d	breast
HT704B1	HT704B1-U41	200	xenium	3d	breast
HT704B1	HT704B1-U43	210	codex	3d	breast
HT704B1	HT704B1-U44	215	he	3d	breast
HT704B1	HT704B1-U47	230	cosmx	3d	breast
HT704B1	HT704B1-U48	235	he	3d	breast
HT704B1	HT704B1-U50	245	xenium	3d	breast
HT704B1	HT704B1-U51	250	visiumhd	3d	breast
HT704B1	HT704B1-U53	260	codex	3d	breast
HT704B1	HT704B1-U54	265	he	3d	breast
HT704B1	HT704B1-U56	275	cosmx	3d	breast
HT704B1	HT704B1-U57	280	he	3d	breast
HT704B1	HT704B1-U60	295	codex	3d	breast
HT704B1	HT704B1-U61	300	he	3d	breast
HT704B1	HT704B1-U65	320	he	3d	breast
HT704B1	HT704B1-U68	335	codex	3d	breast
HT704B1	HT704B1-U69	340	he	3d	breast
HT704B1	HT704B1-U73	360	he	3d	breast
HT704B1	HT704B1-U76	375	codex	3d	breast
HT704B1	HT704B1-U81	400	he	3d	breast
HT704B1	HT704B1-U82	405	codex	3d	breast
HT704B1	HT704B1-U84	415	he	3d	breast
HT704B1	HT704B1-U85	420	codex	3d	breast
HT704B1	HT704B1-U91	450	codex	3d	breast
HT704B1	HT704B1-U90	455	he	3d	breast
HT704B1	HT704B1-U93	460	he	3d	breast
HT891Z1	HT891Z1-U1	0	xenium	3d	prostate
HT891Z1	HT891Z1-U4	10	he	3d	prostate
HT891Z1	HT891Z1-U2	15	visiumhd	3d	prostate
HT891Z1	HT891Z1-U5	20	he	3d	prostate
HT891Z1	HT891Z1-U6	25	he	3d	prostate
HT891Z1	HT891Z1-U7	30	he	3d	prostate
HT891Z1	HT891Z1-U14	65	codex	3d	prostate
HT891Z1	HT891Z1-U21	100	xenium	3d	prostate
HT891Z1	HT891Z1-U28	135	he	3d	prostate
HT891Z1	HT891Z1-U29	140	he	3d	prostate
HT891Z1	HT891Z1-U30	145	he	3d	prostate
HT891Z1	HT891Z1-U31	150	xenium	3d	prostate
HT891Z1	HT891Z1-U32	155	codex	3d	prostate
HT891Z1	HT891Z1-U33	160	visiumhd	3d	prostate
HT891Z1	HT891Z1-U35	170	he	3d	prostate
HT891Z1	HT891Z1-U40	195	codex	3d	prostate
HT891Z1	HT891Z1-U41	200	codex	3d	prostate
HT891Z1	HT891Z1-U43	210	codex	3d	prostate
HT891Z1	HT891Z1-U44	215	xenium	3d	prostate
HT891Z1	HT891Z1-U45	220	codex	3d	prostate
HT891Z1	HT891Z1-U46	225	codex	3d	prostate
HT891Z1	HT891Z1-U47	230	he	3d	prostate
HT891Z1	HT891Z1-U48	235	he	3d	prostate
HT891Z1	HT891Z1-U49	240	he	3d	prostate
HT891Z1	HT891Z1-U50	245	he	3d	prostate
HT891Z1	HT891Z1-U57	280	cosmx	3d	prostate
HT891Z1	HT891Z1-U58	285	codex	3d	prostate
HT891Z1	HT891Z1-U59	290	xenium	3d	prostate
HT891Z1	HT891Z1-U60	295	cosmx	3d	prostate
HT891Z1	HT891Z1-U66	325	he	3d	prostate
HT891Z1	HT891Z1-U68	335	he	3d	prostate
HT891Z1	HT891Z1-U69	340	xenium	3d	prostate
HT891Z1	HT891Z1-U70	345	he	3d	prostate
HT891Z1	HT891Z1-U79	390	codex	3d	prostate
HT891Z1	HT891Z1-U81	400	xenium	3d	prostate
HT891Z1	HT891Z1-U84	415	he	3d	prostate
HT891Z1	HT891Z1-U89	440	he	3d	prostate
HT891Z1	HT891Z1-U90	445	he	3d	prostate
HT891Z1	HT891Z1-U93	460	codex	3d	prostate
HT891Z1	HT891Z1-U94	465	xenium	3d	prostate
HT891Z1	HT891Z1-U101	500	he	3d	prostate
HT891Z1	HT891Z1-U102	505	he	3d	prostate
HT891Z1	HT891Z1-U103	510	codex	3d	prostate
HT891Z1	HT891Z1-U104	515	xenium	3d	prostate
HT891Z1	HT891Z1-U106	525	he	3d	prostate
HT891Z1	HT891Z1-U107	530	he	3d	prostate
HT891Z1	HT891Z1-U108	535	codex	3d	prostate
HT891Z1	HT891Z1-U109	540	codex	3d	prostate
HT891Z1	HT891Z1-U110	545	codex	3d	prostate
HT891Z1	HT891Z1-U111	550	codex	3d	prostate
HT891Z1	HT891Z1-U113	560	codex	3d	prostate
HT891Z1	HT891Z1-U114	565	he	3d	prostate
HT891Z1	HT891Z1-U115	570	he	3d	prostate
HT891Z1	HT891Z1-U116	575	he	3d	prostate
HT913Z1	HT913Z1-U1	0	xenium	3d	prostate
HT913Z1	HT913Z1-U2	5	codex	3d	prostate
HT913Z1	HT913Z1-U3	10	he	3d	prostate
HT913Z1	HT913Z1-U5	20	he	3d	prostate
HT913Z1	HT913Z1-U7	30	he	3d	prostate
HT913Z1	HT913Z1-U9	40	he	3d	prostate
HT913Z1	HT913Z1-U10	45	he	3d	prostate
HT913Z1	HT913Z1-U11	50	xenium	3d	prostate
HT913Z1	HT913Z1-U12	55	codex	3d	prostate
HT913Z1	HT913Z1-U13	60	he	3d	prostate
HT913Z1	HT913Z1-U15	70	he	3d	prostate
HT913Z1	HT913Z1-U17	80	he	3d	prostate
HT913Z1	HT913Z1-U19	90	he	3d	prostate
HT913Z1	HT913Z1-U21	100	xenium	3d	prostate
HT913Z1	HT913Z1-U22	105	codex	3d	prostate
HT913Z1	HT913Z1-U24	115	he	3d	prostate
HT913Z1	HT913Z1-U26	125	he	3d	prostate
HT913Z1	HT913Z1-U28	135	he	3d	prostate
HT913Z1	HT913Z1-U30	145	he	3d	prostate
HT913Z1	HT913Z1-U33	160	xenium	3d	prostate
HT913Z1	HT913Z1-U34	165	xenium	3d	prostate
HT913Z1	HT913Z1-U35	170	xenium	3d	prostate
HT913Z1	HT913Z1-U36	175	he	3d	prostate
HT913Z1	HT913Z1-U38	185	he	3d	prostate
HT913Z1	HT913Z1-U40	195	he	3d	prostate
HT913Z1	HT913Z1-U41	200	codex	3d	prostate
HT913Z1	HT913Z1-U42	205	he	3d	prostate
HT913Z1	HT913Z1-U44	215	he	3d	prostate
HT913Z1	HT913Z1-U46	225	he	3d	prostate
HT913Z1	HT913Z1-U48	235	he	3d	prostate
HT913Z1	HT913Z1-U50	245	he	3d	prostate
HT913Z1	HT913Z1-U51	250	codex	3d	prostate
HT913Z1	HT913Z1-U52	255	codex	3d	prostate
HT913Z1	HT913Z1-U53	260	codex	3d	prostate
HT913Z1	HT913Z1-U54	265	codex	3d	prostate
HT913Z1	HT913Z1-U55	270	he	3d	prostate
HT913Z1	HT913Z1-U57	280	he	3d	prostate
HT913Z1	HT913Z1-U61	300	xenium	3d	prostate
HT913Z1	HT913Z1-U62	305	codex	3d	prostate
HT913Z1	HT913Z1-U63	310	he	3d	prostate
HT913Z1	HT913Z1-U65	320	he	3d	prostate
HT913Z1	HT913Z1-U67	330	he	3d	prostate
HT913Z1	HT913Z1-U69	340	he	3d	prostate
HT913Z1	HT913Z1-U71	350	codex	3d	prostate
HT913Z1	HT913Z1-U72	355	he	3d	prostate
HT913Z1	HT913Z1-U74	365	he	3d	prostate
HT913Z1	HT913Z1-U76	375	he	3d	prostate
HT913Z1	HT913Z1-U78	385	he	3d	prostate
HT913Z1	HT913Z1-U80	395	he	3d	prostate
HT913Z1	HT913Z1-U81	400	xenium	3d	prostate
HT913Z1	HT913Z1-U82	405	codex	3d	prostate
HT913Z1	HT913Z1-U83	410	he	3d	prostate
HT913Z1	HT913Z1-U85	420	he	3d	prostate
HT913Z1	HT913Z1-U87	430	he	3d	prostate
HT913Z1	HT913Z1-U89	440	he	3d	prostate
HT913Z1	HT913Z1-U91	450	codex	3d	prostate
HT913Z1	HT913Z1-U92	455	he	3d	prostate
HT913Z1	HT913Z1-U94	465	he	3d	prostate
HT913Z1	HT913Z1-U96	475	he	3d	prostate
HT913Z1	HT913Z1-U99	490	he	3d	prostate
HT913Z1	HT913Z1-U101	500	xenium	3d	prostate
HT913Z1	HT913Z1-U102	505	codex	3d	prostate
HT913Z1	HT913Z1-U103	510	he	3d	prostate
HT913Z1	HT913Z1-U106	525	he	3d	prostate
HT913Z1	HT913Z1-U108	535	he	3d	prostate
HT913Z1	HT913Z1-U110	545	he	3d	prostate
HT913Z1	HT913Z1-U111	550	codex	3d	prostate
HT913Z1	HT913Z1-U112	555	he	3d	prostate
HT913Z1	HT913Z1-U115	570	he	3d	prostate
HT913Z1	HT913Z1-U117	580	he	3d	prostate
HT913Z1	HT913Z1-U119	590	he	3d	prostate
HT913Z1	HT913Z1-U120	595	he	3d	prostate
HT913Z1	HT913Z1-U121	600	codex	3d	prostate
HT913Z1	HT913Z1-U122	605	he	3d	prostate
HT913Z1	HT913Z1-U124	615	he	3d	prostate
HT913Z1	HT913Z1-U125	620	codex	3d	prostate
SP006Z1	SP006Z1-C8-U1	0	xenium	3d	prostate
SP006Z1	SP006Z1-C8-U3	10	he	3d	prostate
SP006Z1	SP006Z1-C8-U5	20	xenium	3d	prostate
SP006Z1	SP006Z1-C8-U7	30	xenium	3d	prostate
SP006Z1	SP006Z1-C8-U8	35	codex	3d	prostate
SP006Z1	SP006Z1-C8-U9	40	he	3d	prostate
SP006Z1	SP006Z1-C8-U12	55	xenium	3d	prostate
SP006Z1	SP006Z1-C8-U14	65	codex	3d	prostate
SP006Z1	SP006Z1-C8-U18	85	xenium	3d	prostate
SP006Z1	SP006Z1-C8-U19	90	codex	3d	prostate
SP006Z1	SP006Z1-C8-U20	95	xenium	3d	prostate
SP006Z1	SP006Z1-C8-U21	100	codex	3d	prostate
SP006Z1	SP006Z1-C8-U23	110	codex	3d	prostate
SP006Z1	SP006Z1-C8-U24	115	codex	3d	prostate
SP017Z1	SP017Z1-U1	0	visium	3d	prostate
SP017Z1	SP017Z1-U2	5	xenium	3d	prostate
SP017Z1	SP017Z1-U3	10	codex	3d	prostate
SP017Z1	SP017Z1-U5	20	he	3d	prostate
SP017Z1	SP017Z1-U9	40	xenium	3d	prostate
SP017Z1	SP017Z1-U10	45	codex	3d	prostate
SP017Z1	SP017Z1-U12	55	he	3d	prostate
SP017Z1	SP017Z1-U16	105	visium	3d	prostate
SP017Z1	SP017Z1-U17	120	xenium	3d	prostate
SP017Z1	SP017Z1-U18	125	codex	3d	prostate
SP017Z1	SP017Z1-U20	135	he	3d	prostate
SP017Z1	SP017Z1-U24	155	xenium	3d	prostate
SP017Z1	SP017Z1-U25	160	codex	3d	prostate"""), sep='\t')
meta_3d

        case   section_id  z_depth (microns) data_type cohort   disease
0    HT206B1   HT206B1-U1                  0    xenium     3d    breast
1    HT206B1   HT206B1-U4                  5        he     3d    breast
2    HT206B1   HT206B1-U2                 15     codex     3d    breast
3    HT206B1   HT206B1-U5                 20     codex     3d    breast
4    HT206B1   HT206B1-U8                 40    xenium     3d    breast
..       ...          ...                ...       ...    ...       ...
228  SP017Z1  SP017Z1-U17                120    xenium     3d  prostate
229  SP017Z1  SP017Z1-U18                125     codex     3d  prostate
230  SP017Z1  SP017Z1-U20                135        he     3d  prostate
231  SP017Z1  SP017Z1-U24                155    xenium     3d  prostate
232  SP017Z1  SP017Z1-U25                160     codex     3d  prostate

[233 rows x 6 columns]

In [4]:
section_meta = pd.read_csv(StringIO("""Case	Assay_Type	Section_ID	Tumor_Type	Site
SP003Z1	Xenium	SP003Z1-Fp1Us1_1	Primary	Prostate
SP017Z1	Xenium	SP017Z1-Fp1B27Us1_17	Primary	Prostate
SP017Z1	Xenium	SP017Z1-Fp1B27Us1_2	Primary	Prostate
SP017Z1	Xenium	SP017Z1-Fp1B27Us1_24	Primary	Prostate
SP017Z1	Xenium	SP017Z1-Fp1B27Us1_9	Primary	Prostate
SP003Z1	Xenium	SP003Z1-Fp1A15Us1_1	Primary	Prostate
SP004Z1	Xenium	SP004Z1-Fp1B17Us2_1	Primary	Prostate
SP005Z1	Xenium	SP005Z1-Fp1A25Us1_1	Primary	Prostate
SP006Z1	Xenium	SP006Z1-Fp1C8Us1_1	Primary	Prostate
SP008Z1	Xenium	SP008Z1-Fp1F15U1	Primary	Prostate
SP009Z1	Xenium	SP009Z1-Fp1B14U1	Primary	Prostate
SP012Z1	Xenium	SP012Z1-Fp1-A2U3	Primary	Prostate
SP015Z1	Xenium	SP015Z1-Fp1A1U3	Primary	Prostate
SP006Z1	Xenium	SP006Z1-Fp1C8Us2_1	Primary	Prostate
SP006Z1	Xenium	SP006Z1-Fp1C8Us2_12	Primary	Prostate
SP006Z1	Xenium	SP006Z1-Fp1C8Us2_18	Primary	Prostate
SP006Z1	Xenium	SP006Z1-Fp1C8Us2_20	Primary	Prostate
SP006Z1	Xenium	SP006Z1-Fp1C8Us2_5	Primary	Prostate
SP006Z1	Xenium	SP006Z1-Fp1C8Us2_7	Primary	Prostate
HT814Z1	Xenium	HT814Z1-S1H1Fp1Us1_3	Primary	Prostate
HT817Z1	Xenium	HT817Z1-S1H1Fp1Us1_2	Primary	Prostate
SP007Z1	Xenium	SP007Z1-Fp1A10Us2_1	Primary	Prostate
HT832Z1	Xenium	HT832Z1-S1H1Fp1U1	Primary	Prostate
SP016Z1	Xenium	SP016Z1-Fp1B28U1	Primary	Prostate
HT849Z1	Xenium	HT849Z1-S1H2Fp1U1	Primary	Prostate
HT852Z1	Xenium	HT852Z1-S1H1Fp1U1	Primary	Prostate
SP011Z1	Xenium	SP011Z1-Fp1-A15U1	Primary	Prostate
SP014Z1	Xenium	SP014Z1-Fp1A29U1	Primary	Prostate
HT891Z1	Xenium	HT891Z1-S2H3Fp1U1	Primary	Prostate
HT891Z1	Xenium	HT891Z1-S2H3Fp1U21	Primary	Prostate
HT891Z1	Xenium	HT891Z1-S2H3Fp1U32	Primary	Prostate
HT891Z1	Xenium	HT891Z1-S2H3Fp1U44	Primary	Prostate
HT891Z1	Xenium	HT891Z1-S2H3Fp1U59	Primary	Prostate
HT891Z1	Xenium	HT891Z1-S2H3Fp1U69	Primary	Prostate
HT891Z1	Xenium	HT891Z1-S2H3Fp1U104	Primary	Prostate
HT891Z1	Xenium	HT891Z1-S2H3Fp1U81	Primary	Prostate
HT891Z1	Xenium	HT891Z1-S2H3Fp1U94	Primary	Prostate
HT913Z1	Xenium	HT913Z1-S2H1Fp1U101	Primary	Prostate
HT913Z1	Xenium	HT913Z1-S2H1Fp1U33	Primary	Prostate
HT913Z1	Xenium	HT913Z1-S2H1Fp1U34	Primary	Prostate
HT913Z1	Xenium	HT913Z1-S2H1Fp1U35	Primary	Prostate
HT913Z1	Xenium	HT913Z1-S2H1Fp1U61	Primary	Prostate
HT913Z1	Xenium	HT913Z1-S2H1Fp1U81	Primary	Prostate
HT913Z1	Xenium	HT913Z1-S2H1Fp1U1	Primary	Prostate
HT913Z1	Xenium	HT913Z1-S2H1Fp1U11	Primary	Prostate
HT913Z1	Xenium	HT913Z1-S2H1Fp1U21	Primary	Prostate
HT913Z1	Xenium	HT913Z1-S1H1Fp1U1	Primary	Prostate
HT913Z1	Xenium	HT913Z1-S1H1Fp1U11	Primary	Prostate
HT913Z1	Xenium	HT913Z1-S1H1Fp1U8	Primary	Prostate
SP048Z1	Xenium	SP048Z1-Fp1C27U1	Primary	Prostate
SP016Z1	Xenium	SP016Z1-Fp1B28U2	Primary	Prostate
HT832Z1	Xenium	HT832Z1-S1H1Fp1U2	Primary	Prostate
HT1011Z1	Xenium	HT1011Z1-S1H3Fp1U1	Primary	Prostate
HT206B1	Xenium	HT206B1-H2L1Us1_9	Primary	Breast
HT206B1	Xenium	HT206B1-H2L1Us1_17	Primary	Breast
HT206B1	Xenium	HT206B1-H2L1Us1_1	Primary	Breast
HT206B1	Xenium	HT206B1-H2L1Us1_24	Primary	Breast
HT206B1	Xenium	HT206B1-H2L1Us1_8	Primary	Breast
HT206B1	Xenium	HT206B1-H2L1Us1_15	Primary	Breast
HT591B1	Xenium	HT591B1-S1H1Fp1Us1_1	Primary	Breast
HT704B1	Xenium	HT704B1-S1H3Fp1U1	Primary	Breast
HT704B1	Xenium	HT704B1-S1H3Fp1U17	Primary	Breast
HT704B1	Xenium	HT704B1-S1H3Fp1U26	Primary	Breast
HT704B1	Xenium	HT704B1-S1H3Fp1U33	Primary	Breast
HT704B1	Xenium	HT704B1-S1H3Fp1U41	Primary	Breast
HT704B1	Xenium	HT704B1-S1H3Fp1U50	Primary	Breast
1581620AU1	Xenium	1581620AU1	Primary	Breast
1654977AU1	Xenium	1654977AU1	Primary	Breast
HT727B1	Xenium	HT727B1-S1H4Fp1U1	Primary	Breast
1661918aU1	Xenium	1661918aU1	Primary	Breast
1607059U1	Xenium	1607059U1	Primary	Breast
HT944B1	Xenium	HT944B1-S2H2bFpU1	Primary	Breast
SP048Z1	Xenium	SP048Z1-Fp1C27U2	Primary	Prostate
SP051Z1	Xenium	SP051Z1-Fp1F1U2	Primary	Prostate
SP050Z1	Xenium	SP050Z1-Fp1A1U2	Primary	Prostate
SP012Z1	CosMx	SP012Z1-Fp1A2-Ux	Primary	Prostate
SP012Z1	CosMx	SP012Z1-Fp1A15-Ux	Primary	Prostate
SP005Z1	CosMx	SP005Z1-Fp1A25-Ux	Primary	Prostate
HT913Z1	CosMx	HT913Z1-S1H1Fp1	Primary	Prostate
HT891Z1	CosMx	HT891Z1-S2H1Fp1	Primary	Prostate
HT891Z1	CosMx	HT891Z1-S2H4Fp1	Primary	Prostate
HT891Z1	CosMx	HT891Z1-S2H3FP1U57	Primary	Prostate
HT891Z1	CosMx	HT891Z1-S2H3FP1U60	Primary	Prostate
HT938Z1	CosMx	HT938Z1-S1H1FP1U1	Primary	Prostate
HT997Z1	CosMx	HT997Z1-S1H1FP1U1	Primary	Prostate
HT935Z1	CosMx	HT935Z1-S1H1FP1U2	Primary	Prostate
HT206B1	CosMx	HT206B1-H2L1U23_1	Primary	Breast
HT704B1	CosMx	HT704B1-S1H3Fp1_U14	Primary	Breast
HT704B1	CosMx	HT704B1-S1H3Fp1_U22	Primary	Breast
HT704B1	CosMx	HT704B1-S1H3Fp1_U47	Primary	Breast
HT704B1	CosMx	HT704B1-S1H3Fp1_U56	Primary	Breast
HT891Z1	VisiumHD	HT891Z1-S2H3Fp1U2	Primary	Prostate
HT891Z1	VisiumHD	HT891Z1-S2H3Fp1U33	Primary	Prostate
HT935Z1	VisiumHD	HT935Z1-S1H1Fp1U1	Primary	Prostate
HT704B1	VisiumHD	HT704B1-S1H3Fp1U2	Primary	Breast
HT704B1	VisiumHD	HT704B1-S1H3Fp1U51	Primary	Breast
HT935Z1	VisiumHD	HT935Z1-S1H1Fp1U2	Primary	Prostate
HT727B1	VisiumHD	HT727B1-S1H4Fp1U1	Primary	Breast
HT206B1	Visium	HT206B1-S1Fc1U1Z1B1	Primary	Breast
HT206B1	Visium	HT206B1-S1Fc1U2Z1B1	Primary	Breast
HT206B1	Visium	HT206B1-S1Fc1U3Z1B1	Primary	Breast
HT206B1	Visium	HT206B1-S1Fc1U4Z1B1	Primary	Breast
HT206B1	Visium	HT206B1-S1Fc1U5Z1B1	Primary	Breast
HT297B1	Visium	HT297B1-S1H1Fc2U1Z1Bs1	Primary	Breast
HT308B1	Visium	HT308B1-S1H1Fc2U1Z1Bs1	Primary	Breast
HT308B1	Visium	HT308B1-S1H5Fc2U1Z1Bs1	Primary	Breast
HT308B1	Visium	HT308B1-S1H4Fc2U1Z1Bs1	Primary	Breast
HT323B1	Visium	HT323B1-S1H1Fc2U1Z1Bs1	Primary	Breast
HT339B1	Visium	HT339B1-S1H3Fc2U1Z1Bs1	Primary	Breast
HT339B1	Visium	HT339B1-S1H3Fc2U2Bs2	Primary	Breast
HT397B1	Visium	HT397B1-S1H3Fs1U1Bp1	Primary	Breast
HT397B1	Visium	HT397B1-S1H2Fs4U1Bp1	Primary	Breast
HT397B1	Visium	HT397B1-S1H3A1U1Bp1	Primary	Breast
HT397B1	Visium	HT397B1-S1H3A1U21Bp1	Primary	Breast
HT397B1	Visium	HT397B1-S1H3A1U41Bp1	Primary	Breast
HT397B1	Visium	HT397B1-S1H3A1U61Bp1	Primary	Breast
HT425B1	Visium	HT425B1-S1H2Fs1U2Bp1	Primary	Breast
HT480B1	Visium	HT480B1-S1H1Fs1U1Bp1	Primary	Breast
HT480B1	Visium	HT480B1-S1H3Fs1U1Bp1	Primary	Breast
HT480B1	Visium	HT480B1-S1H1Fs1U2Bp1	Primary	Breast
HT486B1	Visium	HT486B1-S1H1Fs1U1Bp1	Primary	Breast
HT486B1	Visium	HT486B1-S1H1Fs1U2Bp1	Primary	Breast
S18-9906	Visium	SP017Z1-Fp1B27Us1_1Bp1	Primary	Prostate
S18-9906	Visium	SP017Z1-Fp1B27Us1_16Bp1	Primary	Prostate
S18-14960	Visium	SP060Z1-Fp1U1Bp1	Primary	Prostate
S18-9251	Visium	SP008Z1-Fp1F15U1Bp1	Primary	Prostate"""), sep='\t')
section_meta

          Case Assay_Type               Section_ID Tumor_Type      Site
0      SP003Z1     Xenium         SP003Z1-Fp1Us1_1    Primary  Prostate
1      SP017Z1     Xenium     SP017Z1-Fp1B27Us1_17    Primary  Prostate
2      SP017Z1     Xenium      SP017Z1-Fp1B27Us1_2    Primary  Prostate
3      SP017Z1     Xenium     SP017Z1-Fp1B27Us1_24    Primary  Prostate
4      SP017Z1     Xenium      SP017Z1-Fp1B27Us1_9    Primary  Prostate
..         ...        ...                      ...        ...       ...
121    HT486B1     Visium     HT486B1-S1H1Fs1U2Bp1    Primary    Breast
122   S18-9906     Visium   SP017Z1-Fp1B27Us1_1Bp1    Primary  Prostate
123   S18-9906     Visium  SP017Z1-Fp1B27Us1_16Bp1    Primary  Prostate
124  S18-14960     Visium         SP060Z1-Fp1U1Bp1    Primary  Prostate
125   S18-9251     Visium      SP008Z1-Fp1F15U1Bp1    Primary  Prostate

[126 rows x 5 columns]

In [11]:
cases_2d = set(section_meta['Case'])
cases_3d = set(meta_3d['case'])
cases_2d.intersection(cases_3d)

{'HT206B1', 'HT397B1', 'HT704B1', 'HT891Z1', 'HT913Z1', 'SP006Z1', 'SP017Z1'}

In [40]:
old = """HT110B1
HT206B1
HT323B1
HT339B2
HT397B1
HT565B1
HT591B1
HT704B1
HT944B1
HT959B1
HT771Z1
HT814Z1
HT817Z1
HT832Z1
HT849Z1
HT852Z1
HT891Z1
HT913Z1
HT935Z1
HT957Z1
SP003Z1
SP004Z1
SP005Z1
SP006Z1
SP007Z1
SP008Z1
SP009Z1
SP010Z1
SP011Z1
SP012Z1
SP013Z1
SP014Z1
SP015Z1
SP016Z1
SP017Z1""".split('\n')

for x in sorted(cases_2d - set(old)):
    print(x)

1581620AU1
1607059U1
1654977AU1
1661918aU1
HT1011Z1
HT297B1
HT308B1
HT339B1
HT425B1
HT480B1
HT486B1
HT727B1
HT938Z1
HT997Z1
S18-14960
S18-9251
S18-9906
SP048Z1
SP050Z1
SP051Z1

## counting wet lab people

In [65]:
meta = section_meta = pd.read_csv(StringIO("""HT270P1-S1H1A1Fp1Us1_1	Houston	xenium
HT448C1-Th1K2Fp1Us1_1	Houston	xenium
HT591B1-S1H1Fp1Us1_1	Houston	xenium
S17-38539-B4Fp1Us2_1	Houston	xenium
SN064H1-Ma1Fd1Us1_1	Houston	xenium
HT206B1-H2L1Us1_16	Houston	xenium
HT206B1-H2L1Us1_24	Houston	xenium
HT206B1-H2L1Us1_8	Houston	xenium
PKD-3908-K2200452U5	Houston	xenium
S18-15142Fp1Us1_1	Houston	xenium
S18-9906-B27Us1_17	Houston	xenium
S18-9906-B27Us1_2	Houston	xenium
S18-9906-B27Us1_24	Houston	xenium
S18-9906-B27Us1_9	Houston	xenium
HT206B1-H2L1Us1_1	Houston	xenium
HT206B1-H2L1Us1_17	Houston	xenium
HT206B1-H2L1Us1_9	Houston	xenium
HT344P1-S1H1A1Us1_1	Houston	xenium
HT434P1-S1H2Fp1Us1_1	Houston	xenium
WUR238-A3Us2_1	Houston	xenium
HT714P1-S1H1Fp1Us1_1	Houston	xenium
S12-3551-A9Us1_1	Houston	xenium
S20-20244-D23Us1_1	Houston	xenium
S23-33446-A32Us1_1	Houston	xenium
S18-11798-A15Us1_1	Houston	xenium
S18-15142-B17Us2_1	Houston	xenium
S18-18215-A25Us1_1	Houston	xenium
S18-5591-C8Us1_1	Houston	xenium
S20-20021-B1U1	Houston	xenium
S23-30813-A1U1	Houston	xenium
SN004H1-Md1Fp2U3	Houston	xenium
SN032H1-Md1Fp2U1	Houston	xenium
SN039H1-Md1Fp2U1	Houston	xenium
S12-3551-A9Us2_1	Houston	xenium
S12-3551-A9Us2_13	Houston	xenium
S12-3551-A9Us2_19	Houston	xenium
S12-3551-A9Us2_25	Houston	xenium
S12-3551-A9Us2_31	Houston	xenium
S12-3551-A9Us2_7	Houston	xenium
S18-9251-F15U1	Houston	xenium
S18-9259-B14U1	Houston	xenium
S19-41530-D1U3	Houston	xenium
S21-11816-A2U3	Houston	xenium
S21-44455-A1U3	Houston	xenium
S22-53426-A1U3	Houston	xenium
20210419-NMK3F-Fp1U1	Houston	xenium
20210419-NMK3M-Fp1U1	Houston	xenium
20210423-NMK12F-Fp1U1	Houston	xenium
20210423-NMK12M-Fp1U1	Houston	xenium
20210907-NMK92M-Fp1U1	Houston	xenium
20210908-NMK92F-Fp1U1	Houston	xenium
230320-P1F1MnR-Fp1U1	Houston	xenium
230320-P1M3MnR-Fp1U1	Houston	xenium
S18-5591-C8Us2_1	Houston	xenium
S18-5591-C8Us2_12	Houston	xenium
S18-5591-C8Us2_18	Houston	xenium
S18-5591-C8Us2_20	Houston	xenium
S18-5591-C8Us2_5	Houston	xenium
S18-5591-C8Us2_7	Houston	xenium
S18-25943-A7Us1_1	Houston	xenium
S18-25943-A7Us1_11	Houston	xenium
S18-25943-A7Us1_4	Houston	xenium
S18-25943-A7Us1_8	Houston	xenium
C3L-01287-11Us1_1	Houston	xenium
C3N-01200-11Us1_1	Houston	xenium
PKD-3908-K2200447U1	Houston	xenium
PKD-3912-K2200487U1	Houston	xenium
PKD-3912-K2200493U1	Houston	xenium
20210209-NMK52F-Fp1U1	Houston	xenium
20210209-NMK52M-Fp1U1	Houston	xenium
20210419-NMK3F-Fp1U2	Houston	xenium
20210419-NMK3M-Fp1U2	Houston	xenium
20210423-NMK12F-Fp1U2	Houston	xenium
20210423-NMK12M-Fp1U2	Houston	xenium
PKD-3949-K2300124U1	Houston	xenium
PKD-3949-K2300132U2	Houston	xenium
PKD-3949-K2300134U1	Houston	xenium
SN007H1-Md1Fp2U1	Houston	xenium
SN010H1-Md1Fp2U1	Houston	xenium
SN018H1-Md1Fp2U1	Houston	xenium
C3L-00970-13U1	Houston	xenium
C3N-00733-12U1	Houston	xenium
SN009H1-Md1Fp2U3	Houston	xenium
SN046H1-Md1Fp2U1	Houston	xenium
SN047H1-Md1Fp2U1	Houston	xenium
HT263B1-S1H4L1U1	Xiang	xenium
HT263B1-S1H4L1U1	Xiang	xenium
HT263B1-S1H4L1U1	Xiang	xenium
HT270P1-S1H1A1Us2_1	Xiang	xenium
HT270P1-S1H1A1Us2_1	Xiang	xenium
HT270P1-S1H1A1Us2_1	Xiang	xenium
HT378B1-S1H2A1U1	Xiang	xenium
HT378B1-S1H2A1U1	Xiang	xenium
HT378B1-S1H2A1U1	Xiang	xenium
HT434P1-S1H2Fp1Us2_1	Xiang	xenium
HT434P1-S1H2Fp1Us2_1	Xiang	xenium
HT434P1-S1H2Fp1Us2_1	Xiang	xenium
HT446B1-H4Fp1Us1_1	Xiang	xenium
HT446B1-H4Fp1Us1_1	Xiang	xenium
HT446B1-H4Fp1Us1_1	Xiang	xenium
S16-38794-A3U2	Xiang	xenium
S16-38794-A3U2	Xiang	xenium
S16-38794-A3U2	Xiang	xenium
HT413C1-Th1K4A1Us1_19	Xiang/Houston	xenium
HT413C1-Th1K4A1Us1_2	Xiang/Houston	xenium
HT413C1-Th1K4A1Us1_25	Xiang/Houston	xenium
HT413C1-Th1K4A1Us1_31	Xiang/Houston	xenium
HT413C1-Th1K4A1Us1_36	Xiang/Houston	xenium
HT413C1-Th1K4A1Us1_9	Xiang/Houston	xenium
20240104-NMK12F2U1	Houston	xenium
20240104-NMK12M1U1	Houston	xenium
20240104-NMK28F1U1	Houston	xenium
20240104-NMK28F2U1	Houston	xenium
20240104-NMK28M1U1	Houston	xenium
20240104-NMK28M2U1	Houston	xenium
20240104-NMK12F1U1	Houston	xenium
20240104-NMK12F2U1	Houston	xenium
20240104-NMK12M1U1	Houston	xenium
20240104-NMK12X1U1	Houston	xenium
20240104-NMK12X2U1	Houston	xenium
20240104-NMK12X3U1	Houston	xenium
C3L-00982-11U2	Houston	xenium
C3L-01676-13U2	Houston	xenium
C3L-01929-11U2	Houston	xenium
C3L-02551-11U3	Houston	xenium
C3L-07213-11U2	Houston	xenium
NP23-636-A8U2	Houston	xenium
SN002H1-Ma1Fd2U2	Houston	xenium
SN056H1-Ma1Fd2U2	Houston	xenium
SN064H1-Ma1Fd2U2	Houston	xenium
SN078H1-Ma1Fd2U2	Houston	xenium
HT413C1-Th1K1A4Us1_5	Xiang	xenium
HT413C1-Th1K2A1Us1_7	Xiang	xenium
HT413C1-Th1K3A1Us1_4	Xiang	xenium
S20-11848-B4Us1_2	Xiang	xenium
S21-46983-A3Us1_2	Xiang	xenium
HT714P1-S1H1Fp1Us2_5	Houston	xenium
S17-6773-A2Us1_1	Houston	xenium
S18-11267-A12Us1_6	Houston	xenium
S18-1374-A4Us1_2	Houston	xenium
HT814Z1-S1H1Fp1Us1_3	Xiang	xenium
HT817Z1-S1H1Fp1Us1_2	Xiang	xenium
MB22-00759-A1Us1_1	Xiang	xenium
PB21-00164-A1Us1_1	Xiang	xenium
S18-8795-A10Us2_1	Xiang	xenium
20240208-NMK12F1U1	Houston	xenium
20240208-NMK12F2U1	Houston	xenium
20240208-NMK12M1U1	Houston	xenium
20240208-NMK12M2U1	Houston	xenium
20240208-NMK52F1U1	Houston	xenium
20240208-NMK52M2U1	Houston	xenium
PKD121Ld38D-Mn1Fp1U1	Houston	xenium
PKD124Ld38D-Mn1Fp1U1	Houston	xenium
20230717-MuP1F1U1	Houston	xenium
20230717-MuP1M3U1	Houston	xenium
20240207-Mu52WF2U1	Houston	xenium
20240209-Mu52WM1U1	Houston	xenium
20240212-MuP21F1U1	Houston	xenium
20240212-MuP21M3U1	Houston	xenium
HT282N1-S1H3A4U2	Xiang	xenium
HT338N1-S1H1A1U1	Xiang	xenium
HT338N2-H1FP1U1	Xiang	xenium
HT522N1-Th1K4Fp1U1	Xiang	xenium
HT609N1-S1H1Fp1U1	Xiang	xenium
HT832Z1-S1H1Fp1U1	Xiang	xenium
HT260C1-Th1K1L1U1	Houston	xenium
HT260C1-Th1K1L1U2	Houston	xenium
HT2681-Th1H3L1U2	Houston	xenium
HT268B1-Th1H3L1U1	Houston	xenium
S18-8122-B28U1	Houston	xenium
S19-12431-A1U1	Houston	xenium
HT849Z1-S1H2Fp1U1	Xiang	xenium
HT852Z1-S1H1Fp1U1	Xiang	xenium
PE0054A1-H1Fp1U1	Xiang	xenium
PE0247-H1Fp1U1	Xiang	xenium
PE0301A1-S1H1Fp1U1	Xiang	xenium
S09-12931-B1U1	Xiang	xenium
S20-19258-A3U1	Xiang	xenium
S13-31378-C1U1	Houston	xenium
S13-31378-E5U1	Houston	xenium
S16-44514-B2U1	Houston	xenium
S16-44514-E7U1	Houston	xenium
S20-12521-A15U1	Houston	xenium
S22-44238-A29U1	Houston	xenium
SN001H1-Md1Fp2bUs3_1	Xiang	xenium
SN049H1-Md1Fp2Us1_1	Xiang	xenium
SN059H1-Md1Fp2Us1_1	Xiang	xenium
SN079H1-Md1Fp4Us1_1	Xiang	xenium
SN089H1-Md1Fp2Us1_1	Xiang	xenium
SN091H1-Md1Fp2Us1_1	Xiang	xenium
SN094H1-Md1Fp2Us1_1	Xiang	xenium
HT227P1-S1H1L1U1	Houston	xenium
HT242P1-S1H4L4U1	Houston	xenium
HT243B1-S1H1A4U1	Houston	xenium
HT308B1-S1H5A4U1	Houston	xenium
PE0154U1-Fp1U1	Houston	xenium
PE0200A1-S1H3U1	Houston	xenium
PE0213U1-Fp1U1	Houston	xenium
HT284P1-S1H1A1U1	Xiang	xenium
HT65B1-H1A1A4U1	Xiang	xenium
S16-34821A1U1	Xiang	xenium
S17-19858A1U1	Xiang	xenium
S17-32498A1U1	Xiang	xenium
S18-30740A1U1	Xiang	xenium
SH22-05156A1U1	Xiang	xenium
HT305B1-S1H5A1U1	Xiang	xenium
HT425B1-S1H1Fp1U1	Xiang	xenium
PE0169U1-Fp1U1	Xiang	xenium
PE0218U1-Fp1U1	Xiang	xenium
PE0257U1-Fp2U1	Xiang	xenium
PE0295U1-Fp1U1	Xiang	xenium
SN105H1-Ma1Fp2-5U1	Xiang	xenium
SN106H1-Ma1Fp2-7U1	Xiang	xenium
HT254C1-M1K1L1U1	Xiang	xenium
HT307C1-Th3K1A1U1	Xiang	xenium
HT342C1-M2A1U1	Xiang	xenium
HT489C1-M1Fp1U1	Xiang	xenium
SN014H1-Md1Fp2U1	Xiang	xenium
SN021H1-Md1Fp2U1	Xiang	xenium
SN055H1-Md1Fp4U1	Xiang	xenium
C3L-03372-12U2	Xiang	xenium
C3N-00663-11U2	Xiang	xenium
C3N-01334-13U2	Xiang	xenium
SN064H1-Ma1Fd2Us3_2	Xiang	xenium
SN078H1-Ma1Fd2Us3_1	Xiang	xenium
SN106H1-Ma1Fd2-7U2	Xiang	xenium
SN109R1-Ma1Pt4Fd2U1	Xiang	xenium
S18-5929-C27U2	Houston	xenium
S20-20021-B1U2	Houston	xenium
S20-23195-F1U2	Houston	xenium
S23-26383-A1U2	Houston	xenium
S23-27043-A1U2	Houston	xenium
HT891Z1-S2H3Fp1U1	Houston	xenium
HT891Z1-S2H3Fp1U21	Houston	xenium
HT891Z1-S2H3Fp1U32	Houston	xenium
HT891Z1-S2H3Fp1U44	Houston	xenium
HT891Z1-S2H3Fp1U59	Houston	xenium
HT891Z1-S2H3Fp1U69	Houston	xenium
SN005H1-Md1Fp2U1	Xiang	xenium
SN017H1-Md1Fp2U1	Xiang	xenium
SN028H1-Md1Fp2U1	Xiang	xenium
SN061H1-Md1Fp4U1	Xiang	xenium
SN088H1-Md1Fp2U1	Xiang	xenium
SN090H1-Md1Fp4U1	Xiang	xenium
SN106H1-Ma1Fd2-2U1	Xiang	xenium
SN106H1-Ma1Fd2-9U1	Xiang	xenium
SN107H1-Ma1Fd2-11U1	Xiang	xenium
SN110R1-Ma1Df4Fd2U1	Xiang	xenium
SN110R1-Ma1Pt13Fd2U1	Xiang	xenium
SN111R1-Ma1Df5Fd2U1	Xiang	xenium
C3L-01287-11Us2_1	Xiang	xenium
C3L-03372-12Us3_1	Xiang	xenium
C3N-00663-11U3	Xiang	xenium
HT891Z1-S2H3Fp1U104	Xiang	xenium
HT891Z1-S2H3Fp1U81	Xiang	xenium
HT891Z1-S2H3Fp1U94	Xiang	xenium
HT704B1-S1H3Fp1U1	Houston	xenium
HT704B1-S1H3Fp1U17	Houston	xenium
HT704B1-S1H3Fp1U26	Houston	xenium
HT704B1-S1H3Fp1U33	Houston	xenium
HT704B1-S1H3Fp1U41	Houston	xenium
HT704B1-S1H3Fp1U50	Houston	xenium
SN113R1-Ma1Fd2-2U1	Xiang	xenium
SN114R1-Ma1Fd2-3U1	Xiang	xenium
SN116R1-Ma1Df8Fd2U1	Xiang	xenium
SN119R1-Ma1Fd2-7U1	Xiang	xenium
SN130R1-Ma1Pt2Fd2U1	Xiang	xenium
HT910P1-S1H1Fp1U1	Houston	xenium
PKD-3908-K2200452U7	Houston	xenium
PKD-3912-K2200493U2	Houston	xenium
SN078H1-Ma1Fd1Us4_1	Houston	xenium
SN107H1-Ma1Fd1-11U2	Houston	xenium
HT913Z1-S2H1Fp1U101	Houston	xenium
HT913Z1-S2H1Fp1U33	Houston	xenium
HT913Z1-S2H1Fp1U34	Houston	xenium
HT913Z1-S2H1Fp1U35	Houston	xenium
HT913Z1-S2H1Fp1U61	Houston	xenium
HT913Z1-S2H1Fp1U81	Houston	xenium
HT913Z1-S2H1Fp1U1	Xiang	xenium
HT913Z1-S2H1Fp1U11	Xiang	xenium
HT913Z1-S2H1Fp1U21	Xiang	xenium
SN039H1-Md1Fp2U2	Xiang	xenium
SN091H1-Md1Fp2U2	Xiang	xenium
SN126R1-Ma1Fd2-4U1	Xiang	xenium
H1519519-Fp1U1	Houston	xenium
H1529522-Fp1U1	Houston	xenium
H1529523-Fp1U1	Houston	xenium
HT913Z1-S1H1Fp1U1	Houston	xenium
HT913Z1-S1H1Fp1U11	Houston	xenium
HT913Z1-S1H1Fp1U8	Houston	xenium
SN001H1-Md1Fp2aU1	Xiang	xenium
SN001H1-Md1Fp2aU102	Xiang	xenium
SN001H1-Md1Fp2aU21	Xiang	xenium
SN001H1-Md1Fp2aU81	Xiang	xenium
SN113R1-Ma1Fd2-2U2	Xiang	xenium
SN121R1-Ma1Fd2-5U1	Xiang	xenium
SN126R1-Ma1Fd2-4U1	Xiang	xenium
SN136R1-Ma1Fd2-6U1	Xiang	xenium
SN142R1-Ma1Fd2-3U1	Xiang	xenium
SN001H1-Md1Fp2aU121	Xiang/Xiangwei	xenium
SN001H1-Md1Fp2aU141	Xiang/Xiangwei	xenium
SN001H1-Md1Fp2aU41	Xiang/Xiangwei	xenium
SN001H1-Md1Fp2aU62	Xiang/Xiangwei	xenium
S17-19858A1U2	Xiang	xenium
S18-30740A1U2	Xiang	xenium
S18-30740A1U3	Xiang	xenium
SN121R1-Ma1Fd2-5U2	Xiang	xenium
SN151R1-Ma1Fd2-2U1	Xiang	xenium
SN154R1-Ma1Fd2-1U1	Xiang	xenium
HT282N1-S1H2A1Fp1U1	Xiangwei	xenium
HT293N1-S1H2A1FpU1	Xiangwei	xenium
HT338N2-S1H4Fp1U1	Xiangwei	xenium
HT609N1-S1H2Fp1U1	Xiangwei	xenium
HT870N1-S1H1Fp1U1	Xiangwei	xenium
HT918N1-S1H1Fp1U1	Xiangwei	xenium
SN126R1-Ma1Fd2-4U3	Xiangwei	xenium
SN131R2-Ma1Fd2-12U1	Xiangwei	xenium
SN158R1-Ma1Fd2-4U1	Xiangwei	xenium
S16-26183A1U1	Xiangwei	xenium
S17-5570A1U1	Xiangwei	xenium
S18-24115A1U1	Xiangwei	xenium
S18-30712A1U1	Xiangwei	xenium
S18-6148A1U1	Xiangwei	xenium
S19-34073A1U1	Xiangwei	xenium
S18-5929-C27U1	Xiangwei	xenium
S18-8122-B28U2	Xiangwei	xenium
K2400180U1	Xiangwei	xenium
NP24-445U1	Xiangwei	xenium
S16-44514-E7U2	Xiangwei	xenium
S20-11848-B4U3	Xiangwei	xenium
K2200593-2U1	Xiangwei	xenium
HT227P1-S1H1L1U2	Xiangwei	xenium
HT832Z1-S1H1Fp1U2	Xiangwei	xenium
K2300202-2U1	Xiangwei	xenium
430998-d0U1	Xiang	xenium
827494-d0U1	Xiang	xenium
SN162R1-Ma1Fd2-9U1	Xiang	xenium
SN161R1-Ma1Fd2-3U1	Xiang	xenium
184874-d0U1	Xiang	xenium
SN160R1-Ma1Fd2-15U1	Xiang	xenium
S10-F2U1	Xiang	xenium
S12-13931A1U1	Xiang	xenium
SN169R1-Ma1Fd2-1U1	Xiang	xenium
SN164R1-Ma1Fd2-4U1	Xiang	xenium
C3L-03405-11U1	Xiangwei	xenium
C3L-01048-11U1	Xiangwei	xenium
C3L-01043-14U1	Xiangwei	xenium
S21-35964-H5U1	Xiangwei	xenium
S16-44514-B3U1	Xiangwei	xenium
861190-d0U1	Xiang	xenium
215695-d0U1	Xiang	xenium
853324-d0U1	Xiang	xenium
HT941N1-S1H1Fp1U1	Xiang	xenium
HT973N1-S1H1A2U1	Xiang	xenium
HT901N1-S1H2Fp1U1	Xiang	xenium
HT902N1-S1H1Fp1U1	Xiang	xenium
HT970N1-S1H1Fp1U1	Xiangwei	xenium
HT963N1-S1H1Fp1U1	Xiangwei	xenium
HT958N1-S1H1Fp1U1	Xiangwei	xenium
HT934N1-S2H1Fp1U1	Xiangwei	xenium
S03-40124-A8U1	Xiangwei	xenium
PE0236-H1Fp1U1	Xiangwei	xenium
C3N-03088-12U1	Xiangwei	xenium
S21-1209-A1U1	Xiangwei	xenium
S18-461-A1U1	Xiangwei	xenium
SN174R1-14U1	Xiangwei	xenium
S17-34578-A1U1	Xiangwei	xenium
S19-25371-A1U1	Xiangwei	xenium
S22-3386-A1U1	Xiangwei	xenium
HT060P1-S1R1Fp1U1	Xiang(day 1&2)/Xiangwei (day 3&after)	xenium
HT125P1-S1H4A1L1U1	Xiang(day 1&2)/Xiangwei (day 3&after)	xenium
HT179C1-T1Fp3L5U1	Xiang(day 1&2)/Xiangwei (day 3&after)	xenium
HT061P1-S1P1A1L1U1	Xiang(day 1&2)/Xiangwei (day 3&after)	xenium
HT061P1-S1P1A1L4U1	Xiang(day 1&2)/Xiangwei (day 3&after)	xenium
HT403C1-S1H1A1U1	Xiang(day 1&2)/Xiangwei (day 3&after)	xenium
HT185P1-S1H3L1U1	Xiang(day 1&2)/Xiangwei (day 3&after)	xenium
HT185P1-S1H2L1U1	Xiang(day 1&2)/Xiangwei (day 3&after)	xenium
HT125P1-S1H8A1U1	Xiang(day 1&2)/Xiangwei (day 3&after)	xenium
1581620AU1	Xiangwei	xenium
1658952AU1	Xiangwei	xenium
1654977AU1	Xiangwei	xenium
CMD016C1-Th1Fp6U1	Xiangwei	xenium
K2400432-2U1	Xiangwei	xenium
K1600337PBU1	Xiangwei	xenium
K1600339PBU1	Xiangwei	xenium
NP23-745-B10U1	Xiangwei	xenium
K2400337-2U1	Xiangwei	xenium
K2400267-3U1	Xiangwei	xenium
K2400124-1U1	Xiangwei	xenium
K2400052-3U1	Xiangwei	xenium
C3N-05991-12U1	Xiangwei	xenium
S15-23849-A2U1	Xiangwei	xenium
S15-21169-A1U1	Xiangwei	xenium
S15-1909-D2U1	Xiangwei	xenium
S15-1909-A5U1	Xiangwei	xenium
S15-32775-D4U2	Xiangwei	xenium
S16-38794-E2U1	Xiangwei	xenium
S15-32775-A1U2	Xiangwei	xenium
S16-38794-A4U2	Xiangwei	xenium
S11-41502-A33U1	Xiangwei	xenium
HT413C1-Th1K2A1U2	Xiangwei	xenium
S12-3551-A20U3_1	Xiangwei	xenium
S12-3551-A20U3_2	Xiangwei	xenium
NP22-547A12U1	Xiangwei	xenium
S18-11267-A12U2	Xiangwei	xenium
HT975P1-S1H2Fp1U1	Xiangwei	xenium
S18-5264-B18U1	Xiangwei	xenium
HT943P1-S1H2Fp1U1	Xiangwei	xenium
NP22-980-A11U1	Xiangwei	xenium
NP24-763-B4U1	Xiangwei	xenium
NP24-446-B3U1	Xiangwei	xenium
NP24-89-A15U1	Xiangwei	xenium
S24-34524A1U1	Xiyi/Xiang	xenium
S12-13931A1U2	Xiyi/Xiang	xenium
S14-9876A1U1	Xiyi/Xiang	xenium
S10-F2U2	Xiyi/Xiang	xenium
S13-30035A1U1	Xiyi/Xiang	xenium
S14-11561A1U1	Xiyi/Xiang	xenium
S24-19138A1U1	Xiyi/Xiang	xenium
S13-31378-B1U1	Xiangwei	xenium
S13-31378-E7U1	Xiangwei	xenium
HT472C1-S1H3FP1U1	Xiangwei	xenium
HT472C1-M1FP1U1	Xiangwei	xenium
C3L-00813-11U1	Xiangwei	xenium
C3L-02841-11U1	Xiangwei	xenium
HT1011Z1-S1H3Fp1U1	Xiangwei	xenium
S17-16442-AFR1U1	Xiangwei	xenium
S18-461-A1U2	Xiangwei	xenium
S24-19976-A1U1Q1	Xiangwei	xenium
S24-31988-A1U1	Xiangwei	xenium
S24-18261-A1U1	Xiangwei	xenium
S24-25156-A1U1	Xiangwei	xenium
S24-10657-A2U1Q1	Xiangwei	xenium
S24-10657-A2U1Q2	Xiangwei	xenium
S24-19976-A1U1Q2	Xiangwei	xenium
S24-15022-A1U1	Xiangwei	xenium
S13-18424-B5U1	Xiangwei	xenium
K2200056PBU1	Xiangwei	xenium
K2200045PBU1	Xiangwei	xenium
K1700135U1	Xiangwei	xenium
K2200064PBU1	Xiangwei	xenium
HT1012N1-S1H1Fp1U1	Xiangwei	xenium
HT588N1-H1Fp1U1	Xiangwei	xenium
S13-18424-A1U1	Xiangwei	xenium
HT955N1-S2H1Fp1U1	Xiangwei	xenium
S20-46186-A16U1	Xiangwei	xenium
S14-2647A1U1	Xiyi/Xiang	xenium
S23-56926A1U1	Xiyi/Xiang	xenium
S24-30069A1U1	Xiyi/Xiang	xenium
S24-33389A1U1	Xiyi/Xiang	xenium
S13-35096A1U1	Xiyi/Xiang	xenium
S14-35675A1U1	Xiyi/Xiang	xenium
S13-47674A1U1	Xiyi/Xiang	xenium
HT727B1-S1H4Fp1U1	Xiangwei	xenium
1613496U1	Xiangwei	xenium
1661918aU1	Xiangwei	xenium
1607059U1	Xiangwei	xenium
1664282bU1	Xiangwei	xenium
1584343bU1	Xiangwei	xenium
S21-9049-P4U1	Xiangwei	xenium
S21-35275-M6U1	Xiangwei	xenium
S20-29194-G4U1	Xiangwei	xenium
HT944B1-S2H2bFpU1	Xiangwei	xenium
S21-26312-A4U1	Xiangwei	xenium
K1600337PBU2	Xiangwei	xenium
K1700135U2	Xiangwei	xenium
S14-14053A1U1	Xiang	xenium
S17-24784A1U2	Xiang	xenium
S17-24784A1U1	Xiang	xenium
S16-30080A1U1	Xiang	xenium
S24-3545A1U1	Xiang	xenium
S21-999A1U1	Xiang	xenium
S14-14053A1U2	Xiang	xenium
S11-3564A1U1	Xiang	xenium
S18-36373A1U1	Xiang	xenium
WHIM9I-ALP-440U1	Xiangwei	xenium
WHIM9I-CTL-435U1	Xiangwei	xenium
WHIM16E-ALP-356U1	Xiangwei	xenium
WHIM16E-CTL-361U1	Xiangwei	xenium
655-06D-ALP-5123U1	Xiangwei	xenium
1937-07D-ALP-5110U1	Xiangwei	xenium
RESL10I-ALP-815U1	Xiangwei	xenium
RESL10I-CTL-801U1	Xiangwei	xenium
RESL4-ALP-823U1	Xiangwei	xenium
RESL4-CTL-835U1	Xiangwei	xenium
1937-07D-CTL-5114U1	Xiangwei	xenium
1937-07D-CTL-5114U2	Xiangwei	xenium
655-06D-CTL-5119U1	Xiangwei	xenium
7248-LIV-U1	Xiangwei	xenium
7361-LIV-U1	Xiangwei	xenium
7260-LIV-U1	Xiangwei	xenium
7352-LIV-U1	Xiangwei	xenium
8387M-P8C-U2	Xiangwei	xenium
430F-P8R-U2	Xiangwei	xenium
7001-LIV-U1	Xiangwei	xenium
7239-LIV-U1	Xiangwei	xenium
7239-RIN-U1	Xiangwei	xenium
7435-LIV-U1	Xiangwei	xenium
7448-LIV-U1	Xiangwei	xenium
7450-LIV-U1	Xiangwei	xenium
SP045P1-B12-S1Fp1U1	Xiangwei	xenium
HT856P1-S1H1Fp1U2	Xiangwei	xenium
HT873P1-S1H1Fp1U2	Xiangwei	xenium
SP046P1-D47-S1Fp1U1	Xiangwei	xenium
HT988P1-S1H1Fp1U1	Xiangwei	xenium
HT1046P1-S1H1Fp1U1	Xiangwei	xenium
SP047P1-A7-S1Fp1U1	Xiangwei	xenium
SP044P1-A4-S1Fp1U1	Xiangwei	xenium
HT1041P1-S2H1Fp1U1	Xiangwei	xenium
SP055Z1-A1-TkFp1U1	Xiangwei	xenium
HT190P1-B6-Th2Fp1U1	Xiangwei	xenium
CM478C2-A3-Tp1Fp1U1	Xiangwei	xenium
CM478C1-D4-Tp1Fp1U1	Xiangwei	xenium
CM354C1-A2-Tp1Fp1U1	Xiangwei	xenium
SP054Z1-A1-TkFp1U3Q1	Xiangwei	xenium
SP054Z1-A1-TkFp1U3Q2	Xiangwei	xenium
HT1027P1-S1H1Fp1U1	Xiangwei	xenium
SP059Z1-A1-Tk1Fp1U1	Xiangwei	xenium
SP058Z1-A1-TkFp1U1	Xiangwei	xenium
SP031Z1-A1-TkFp1U2	Xiangwei	xenium
SP057Z1-A1-TkFp1U1	Xiangwei	xenium
S14-18864-A1U1	Xiangwei	xenium
S15-15758-A1U1	Xiangwei	xenium
S14-22950-A1U1	Xiangwei	xenium
S17-32736-A1U1	Xiangwei	xenium
S15-29810-A1U2	Xiangwei	xenium
S16-6602-A1U1	Xiangwei	xenium
S22-8834-A1U1	Xiangwei	xenium
S21-14510-A2U1	Xiangwei	xenium
S21-19998-A1U1Q1	Xiangwei	xenium
S21-19998-A1U1Q2	Xiangwei	xenium
S20-2375-A1U1	Xiangwei	xenium
S14-26651-A1U1	Xiangwei	xenium
SP048Z1-C27-Fp1Us1_63	Xiangwei	xenium
SP048Z1-C27-Fp1Us1_91	Xiangwei	xenium
19503E-U1	Xiangwei	xenium
19502D-U1	Xiangwei	xenium
7259-LIV-U1	Xiangwei	xenium
7250-LIV-U1	Xiangwei	xenium
19499A-U1	Xiangwei	xenium
20744B-U1	Xiangwei	xenium
GM250228-52WK-M2U1	Xiangwei	xenium
GM250102-28WK-M1U1	Xiangwei	xenium
GM250228-52WK-M4U1	Xiangwei	xenium
GM250129-E16.5-M2U1	Xiangwei	xenium
GM230315-E16.5-M1U1	Xiangwei	xenium
GM250129-E16.5-M1U1	Xiangwei	xenium
GM230315-E16.5-M3U1	Xiangwei	xenium
GM241126-P21-M2U1	Xiangwei	xenium
GM241126-P21-M5U1	Xiangwei	xenium
GM250102-92WK-M1U1	Xiangwei	xenium
GM241217-12WK-M5U1	Xiangwei	xenium
GM241217-12WK-M2U1	Xiangwei	xenium
SP078Z1-A1-TkFp1U1	Xiangwei	xenium
SP082Z1-A26-Fp1U1	Xiangwei	xenium
SP080Z1-A25-Fp1U1	Xiangwei	xenium
SP083Z1-A17-Fp1U1	Xiangwei	xenium
SP081Z1-A29-Fp1U1	Xiangwei	xenium
SP079Z1-A14-Fp1U1	Xiangwei	xenium
SN203R1-Ma1Fd2-2U2	Xiangwei	xenium
SP085U1-A1-S1Fp1U1	Xiangwei	xenium
SP087U1-C1-S1Fp1U1	Xiangwei	xenium
SP084U1-A1-S1Fp1U1	Xiangwei	xenium
SP086U1-A1-S1Fp1U1	Xiangwei	xenium
SN209R1-Ma1Fd2-2U2	Xiangwei	xenium
SN200R1-Ma1Fd2-1U2	Xiangwei	xenium
SN207R1-Ma1Fd2-1U2	Xiangwei	xenium
SN198R1-Ma1Fd2-1U2	Xiangwei	xenium
SP088U1-A1-S1Fp1U1	Xiangwei	xenium
WHIM9I-CTL-418U1	Xiangwei	xenium
WHIM20D-ALP-388U1	Xiangwei	xenium
HCI011G-ALP-350U1	Xiangwei	xenium
WHIM20D-CTL-176U1	Xiangwei	xenium
HCI011G-CTL-341U1	Xiangwei	xenium
WHIM9I-ALP-446U1	Xiangwei	xenium
RESL10F-Sap-12465U1	Xiangwei	xenium
RESL10F-Cabo-12467U1	Xiangwei	xenium
RESL10F-CTL-12462U1	Xiangwei	xenium
RESL10-B1-CaboSap-F12473U1	Xiangwei	xenium
RESL4-Sap-16245U1	Xiangwei	xenium
RESL4-B1-CaboSap-F16242LU1	Xiangwei	xenium
RESL4-Cabo-16296U1	Xiangwei	xenium
CM626C1-A7-S1Fp1U1	Xiangwei	xenium
PE0319C1-A4-S1Fp1U1	Xiangwei	xenium
CM1799-A1-Th1Fp1U1	Xiangwei	xenium
CM1691-A3-Th1Fp1U1	Xiangwei	xenium
HT1056N1-S1H1Fp1U1	Xiangwei	xenium
SP074P1-A3-S1Fp1U1	Xiangwei	xenium
SP089P1-B3-S1Fp1U1	Xiangwei	xenium
SP076P1-A7-S1Fp1U18	Xiangwei	xenium
SP090P1-A3-S1Fp1U1	Xiangwei	xenium
WHIM20D-CTL-181U1	Xiangwei	xenium
WHIM20D-ALP-395U1	Xiangwei	xenium
HCI011G-ALP-374U1	Xiangwei	xenium
RESL4-CTL-16262U1	Xiangwei	xenium
WHIM16E-ALP-362U1	Xiangwei	xenium
WHIM16E-CTL-355U1	Xiangwei	xenium
PDMR-274T-ALP-952U1	Xiangwei	xenium
PDMR-274T-CTL-969U1	Xiangwei	xenium
RESL10I-CTL-819U1	Xiangwei	xenium
RESL10I-ALP-862U1	Xiangwei	xenium
WHIM9-RES-732U1	Xiangwei	xenium
HCI011G-CTL-348U1	Xiangwei	xenium
SP092Z1-A25-Fp1U1	Xiangwei	xenium
SP095Z1-A24-Fp1U1	Xiangwei	xenium
SP097Z1-C17-Fp1U1	Xiangwei	xenium
SP096Z1-A15-Fp1U1	Xiangwei	xenium
C3N-01175-11U1	Xiangwei	xenium
SP093Z1-B6-Fp1U1Q1	Xiangwei	xenium
SP093Z1-B6-Fp1U1Q2	Xiangwei	xenium
SP060Z1-Fp1U2	Xiangwei	xenium
C3N-03021-11U1	Xiangwei	xenium
C3N-00958-11U1	Xiangwei	xenium
SP048Z1-C27-Fp1Us1_1	Xiang	xenium
SP048Z1-C27-Fp1Us1_29	Xiang	xenium
CMD007C1-Th1Fp1U1	Xiangwei	xenium
CMD011C1-Th1Fp1U1	Xiangwei	xenium
CMD003C1-Th1Fp1U1	Xiangwei	xenium
CMD014C1-Th1Fp1U1Q1	Xiangwei	xenium
CMD001C1-Th1Fp1U1	Xiangwei	xenium
CMD015C1-Th1Fp1U1	Xiangwei	xenium
CMD014C1-Th1Fp1U1Q2	Xiangwei	xenium
CMD010C1-Th1Fp1U1	Xiangwei	xenium
SN222R1-Ma1Fd2P-1U1	Xiangwei	xenium
SN219R1-Ma1Fd2-1U1	Xiangwei	xenium
SN222R1-Ma1Fd2-1U1	Xiangwei	xenium
SP108U1-A1-S1Fp1U1	Xiangwei	xenium
SP107U1-A1-S1Fp1U1	Xiangwei	xenium
SP106U1-A1-S1Fp1U1	Xiangwei	xenium
SP102U1-A1-S1Fp1U1	Xiangwei	xenium
SP103U1-A1-S1Fp1U1	Xiangwei	xenium
SP104U1-A1-S1Fp1U1	Xiangwei	xenium
SP105U1-A1-S1Fp1U1	Xiangwei	xenium
SP098U1-A1-S1Fp1U1	Xiangwei	xenium
SP100U1-A1-S1Fp1U1	Xiangwei	xenium
SP101U1-A1-S1Fp1U1	Xiangwei	xenium
SP099U1-A1-S1Fp1U1	Xiangwei	xenium
SP109U1-A1-S1Fp1U1	Xiangwei	xenium
SN225R1-Ma1Fd2-1U1	Xiangwei	xenium
SP113U1-A1-S1Fp1U1	Xiangwei	xenium
SP126U1-A1-S1Fp1U1	Xiangwei	xenium
SP119U1-A1-S1Fp1U1	Xiangwei	xenium
SP125U1-A1-S1Fp1U1	Xiangwei	xenium
SP120U1-A1-S1Fp1U1	Xiangwei	xenium
SP121U1-A1-S1Fp1U1	Xiangwei	xenium
SN215R1-Ma1Fd2P-1U1	Xiangwei	xenium
SN224R1-Ma1Fd2-1U1	Xiangwei	xenium
SN227R1-Ma1Fd2-2U1	Xiangwei	xenium
SN221R1-Ma1Fd2P-1U1	Xiangwei	xenium
SN228R1-Ma1Fd2-1U1	Xiangwei	xenium
Moba-73787-Liv1U1	Xiangwei	xenium
Moba-73798-Liv1U1	Xiangwei	xenium
Moba-73795-Lung1U1	Xiangwei	xenium
Moba-73787-Lung1U1	Xiangwei	xenium
Mice_peripheral_nerve_U1	Xiangwei	xenium
GM250310-92wk-M1U1	Xiangwei	xenium
GM250310-92wk-M2U1	Xiangwei	xenium
GM250424-P21-M5U1	Xiangwei	xenium
GM250424-P21-M3U1	Xiangwei	xenium
GM250424-P21-M2U1	Xiangwei	xenium
GM250318-P1-CTF8-LUTU1	Xiangwei	xenium
GM250318-P1-MTF3-LUTU1	Xiangwei	xenium
GM250405-P21-MWF6-LUTU1	Xiangwei	xenium
GM250405-P21-MWM3-LUTU1	Xiangwei	xenium
GM21217-12wk-MWF5-LUTU1	Xiangwei	xenium
GM250129-E165-F9-LUTU1	Xiangwei	xenium
SP112U1-A1-S1Fp1U1	Xiangwei	xenium
SP117U1-A1-S1Fp1U1	Xiangwei	xenium
SN218R1-Ma1Fd2-1U1	Xiangwei	xenium
SP118U1-A1-S1Fp1U1Q1	Xiangwei	xenium
SP118U1-A1-S1Fp1U1Q2	Xiangwei	xenium
SP127U1-A1-S1Fp1U1	Xiangwei	xenium
SP130U1-A1-S1Fp1U1Q2	Xiangwei	xenium
SP129U1-A1-S1Fp1U1	Xiangwei	xenium
SP115U1-A1-S1Fp1U1	Xiangwei	xenium
SP130U1-A1-S1Fp1U1Q1	Xiangwei	xenium
SP114U1-A1-S1Fp1U1	Xiangwei	xenium
SP110U1-A1-S1Fp1U1	Xiangwei	xenium
HT941N1-S1H1Fp1U2	Xiangwei	xenium
HT870N1-S1H1Fp1U2	Xiangwei	xenium
SN089H1-Md1Fp2U2	Xiangwei	xenium
C3L-01469-11U1	Xiangwei	xenium
SN024H1-Md1Fp2U1	Xiangwei	xenium
SN060H1-Md1Fp4U1	Xiangwei	xenium
HT522N1-Th1K4Fp1U2	Xiangwei	xenium
2645-08-UNILVR-U1	Xiangwei	xenium
2593-08-UNILVR-U1	Xiangwei	xenium
HT1094N-S1H1Fp1U1	Xiangwei	xenium
1625069b-U1	Xiangwei	xenium
1607835a-U1	Xiangwei	xenium
1620878a-U1	Xiangwei	xenium
1635696a-U1	Xiangwei	xenium
1623230b-U1	Xiangwei	xenium
1609943a-U1	Xiangwei	xenium
1602852b-U1	Xiangwei	xenium
1619648a-U1	Xiangwei	xenium
1605282b-U1	Xiangwei	xenium
1595216a-U1	Xiangwei	xenium
1622521a-U1	Xiangwei	xenium
1661001a-U1	Xiangwei	xenium
1656870a-U1	Xiangwei	xenium
1625066a-U1	Xiangwei	xenium
3433-07-UNILVR-U1	Xiangwei	xenium
2160-09-UNILVR-U1	Xiangwei	xenium
2444-08B2-UNILVR-U1	Xiangwei	xenium
2444-08B1-UNILVR-U1	Xiangwei	xenium
5125-PNC-U1	Xiangwei	xenium
5125-PND-U1	Xiangwei	xenium
5126-PNC-U1	Xiangwei	xenium
5126-PA-P-U1	Xiangwei	xenium
5108-PB-P-U1	Xiangwei	xenium
5108-PA-U1	Xiangwei	xenium
5108-PD-U1	Xiangwei	xenium
5127-PNC-U1	Xiangwei	xenium
5127-PNA-U1	Xiangwei	xenium
5127-PD-P-U1	Xiangwei	xenium
5125-PA-P-U1	Xiangwei	xenium
5125-PB-U1	Xiangwei	xenium
HS19-06647-1DU1	Xiangwei	xenium
HS18-11250-1CU1	Xiangwei	xenium
HS13-06668-2FU1	Xiangwei	xenium
HS16-40491-2AU1	Xiangwei	xenium
P8R-F-VV_PBPB_S-365U1	Xiangwei	xenium
P8R-M-VV_PBPB-8005U1	Xiangwei	xenium
PKD2320Ld38D-Mn2Fp1U1	Xiangwei	xenium
PKD2318Ld38D-Mn3Fp1U1	Xiangwei	xenium
PKD2278Ld38D-Mn1Fp1U1	Xiangwei	xenium
P8R-F-VV_BB-7085U1	Xiangwei	xenium
P8R-M-VV_PBPB-8047U1	Xiangwei	xenium
P8R-M-Control-7006U1	Xiangwei	xenium
P8R-M-VV_BB-7008U1	Xiangwei	xenium
P8R-M-Control-305U1	Xiangwei	xenium
P8R-M-Control-8194U1	Xiangwei	xenium
P8R-F-Control-368U1	Xiangwei	xenium
P8R-M-VV-6878U1	Xiangwei	xenium
P8R-M-VV_PBPB_S-8200U1	Xiangwei	xenium
SP145S1-L6-S1Fp1U1	Xiangwei	xenium
SP147S1-G2-S1Fp1U1	Xiangwei	xenium
SP138S1-C1-S1Fp1U1	Xiangwei	xenium
SP139S1-I1-S1Fp1U1	Xiangwei	xenium
SP144S1-V1-S1Fp1U1	Xiangwei	xenium
SP152S1-O3-S1Fp1U1	Xiangwei	xenium
SP153S1-F2-S1Fp1U1	Xiangwei	xenium
SP142S1-H5-S1Fp1U1	Xiangwei	xenium
SP143S1-B4-S1Fp1U1	Xiangwei	xenium
SP151S1-F1-S1Fp1U1	Xiangwei	xenium
SP149S1-K1-S1Fp1U1	Xiangwei	xenium
SP148S1-A6-S1Fp1U1	Xiangwei	xenium
SP140S1-C1-Ty1Fp1U1	Xiangwei	xenium
SP168S1-CFR6-S1Fp1U1	Xiangwei	xenium
SP168S1-CFR6-S1Fp1U2	Xiangwei	xenium
SP150S1-A4-S1Fp1U1	Xiangwei	xenium
SP141S1-BFR2-S1Fp1U1	Xiangwei	xenium
SP146S1-F3-S1Fp1U1	Xiangwei	xenium
ML1652M1-Ty1Fp1U1	Xiangwei	xenium
ML1254M1-Ty1Fp1U1	Xiangwei	xenium
ML1329M1-S1Fp1U1	Xiangwei	xenium
ML1646M1-S1Fp1U1	Xiangwei	xenium
ML384M1-S2Fp1U1	Xiangwei	xenium
ML1293M1-S1Fp1U1	Xiangwei	xenium
ML1511M1-S1Fp1U1	Xiangwei	xenium
HS13-06668-2FU2Q1	Xiangwei	xenium
SP165L1-Tr1-B3U1	Xiangwei	xenium
SP163L1-Tr1-A10U1	Xiangwei	xenium
SP161B1-Tr1-B2U1	Xiangwei	xenium
SP167L1-Tr1-B3U1	Xiangwei	xenium
HS13-06668-2FU2Q2	Xiangwei	xenium
SP162B1-Tr1-B5U1	Xiangwei	xenium
SP159B1-Tr1-B1U1	Xiangwei	xenium
HS16-40491-2AU2Q1	Xiangwei	xenium
HS16-40491-2AU2Q2	Xiangwei	xenium
SP160B1-Tr1-B3U1	Xiangwei	xenium
SP166L1-Tr1-B1U1	Xiangwei	xenium
SP158B1-Tr1-A6U1	Xiangwei	xenium
SP164L1-Tr1-B2U1	Xiangwei	xenium
SP174U1-A1-S1Fp1U1Q1	Xiangwei	xenium
SP174U1-A1-S1Fp1U1Q2	Xiangwei	xenium
SP175U1-A1-S1Fp1U1	Xiangwei	xenium
SP176U1-A1-S1Fp1U1	Xiangwei	xenium
SP177U1-A1-S1Fp1U1	Xiangwei	xenium
SP182U1-A1-S1Fp1U1	Xiangwei	xenium
SP183U1-A1-S1Fp1U1	Xiangwei	xenium
SP086U1-A1-S1Fp1U2	Xiangwei	xenium
SP169U1-A1-S1Fp1U2	Xiangwei	xenium
SP170U1-A1-S1Fp1U1	Xiangwei	xenium
SP171U1-A1-S1Fp1U1	Xiangwei	xenium
SP172U1-A1-S1Fp1U1	Xiangwei	xenium
SP173U1-A1-S1Fp1U1	Xiangwei	xenium
SP180U1-A1-S1Fp1U1	Xiangwei	xenium
SP181U1-A1-S1Fp1U1	Xiangwei	xenium"""), sep='\t', header=None, index_col=0)
meta.columns = ['person', 'dtype']
meta

                          person   dtype
0
HT270P1-S1H1A1Fp1Us1_1   Houston  xenium
HT448C1-Th1K2Fp1Us1_1    Houston  xenium
HT591B1-S1H1Fp1Us1_1     Houston  xenium
S17-38539-B4Fp1Us2_1     Houston  xenium
SN064H1-Ma1Fd1Us1_1      Houston  xenium
...                          ...     ...
SP171U1-A1-S1Fp1U1      Xiangwei  xenium
SP172U1-A1-S1Fp1U1      Xiangwei  xenium
SP173U1-A1-S1Fp1U1      Xiangwei  xenium
SP180U1-A1-S1Fp1U1      Xiangwei  xenium
SP181U1-A1-S1Fp1U1      Xiangwei  xenium

[790 rows x 2 columns]

In [66]:
meta

                          person   dtype
0
HT270P1-S1H1A1Fp1Us1_1   Houston  xenium
HT448C1-Th1K2Fp1Us1_1    Houston  xenium
HT591B1-S1H1Fp1Us1_1     Houston  xenium
S17-38539-B4Fp1Us2_1     Houston  xenium
SN064H1-Ma1Fd1Us1_1      Houston  xenium
...                          ...     ...
SP171U1-A1-S1Fp1U1      Xiangwei  xenium
SP172U1-A1-S1Fp1U1      Xiangwei  xenium
SP173U1-A1-S1Fp1U1      Xiangwei  xenium
SP180U1-A1-S1Fp1U1      Xiangwei  xenium
SP181U1-A1-S1Fp1U1      Xiangwei  xenium

[790 rows x 2 columns]

In [67]:
sids = """SP003Z1-Fp1Us1_1
SP017Z1-Fp1B27Us1_17
SP017Z1-Fp1B27Us1_2
SP017Z1-Fp1B27Us1_24
SP017Z1-Fp1B27Us1_9
SP003Z1-Fp1A15Us1_1
SP004Z1-Fp1B17Us2_1
SP005Z1-Fp1A25Us1_1
SP006Z1-Fp1C8Us1_1
SP008Z1-Fp1F15U1
SP009Z1-Fp1B14U1
SP012Z1-Fp1-A2U3
SP015Z1-Fp1A1U3
SP006Z1-Fp1C8Us2_1
SP006Z1-Fp1C8Us2_12
SP006Z1-Fp1C8Us2_18
SP006Z1-Fp1C8Us2_20
SP006Z1-Fp1C8Us2_5
SP006Z1-Fp1C8Us2_7
HT814Z1-S1H1Fp1Us1_3
HT817Z1-S1H1Fp1Us1_2
SP007Z1-Fp1A10Us2_1
HT832Z1-S1H1Fp1U1
SP016Z1-Fp1B28U1
HT849Z1-S1H2Fp1U1
HT852Z1-S1H1Fp1U1
SP011Z1-Fp1-A15U1
SP014Z1-Fp1A29U1
HT891Z1-S2H3Fp1U1
HT891Z1-S2H3Fp1U21
HT891Z1-S2H3Fp1U32
HT891Z1-S2H3Fp1U44
HT891Z1-S2H3Fp1U59
HT891Z1-S2H3Fp1U69
HT891Z1-S2H3Fp1U104
HT891Z1-S2H3Fp1U81
HT891Z1-S2H3Fp1U94
HT913Z1-S2H1Fp1U101
HT913Z1-S2H1Fp1U33
HT913Z1-S2H1Fp1U34
HT913Z1-S2H1Fp1U35
HT913Z1-S2H1Fp1U61
HT913Z1-S2H1Fp1U81
HT913Z1-S2H1Fp1U1
HT913Z1-S2H1Fp1U11
HT913Z1-S2H1Fp1U21
HT913Z1-S1H1Fp1U1
HT913Z1-S1H1Fp1U11
HT913Z1-S1H1Fp1U8
SP048Z1-Fp1C27U1
SP016Z1-Fp1B28U2
HT832Z1-S1H1Fp1U2
HT1011Z1-S1H3Fp1U1
HT206B1-H2L1Us1_9
HT206B1-H2L1Us1_17
HT206B1-H2L1Us1_1
HT206B1-H2L1Us1_24
HT206B1-H2L1Us1_8
HT206B1-H2L1Us1_15
HT591B1-S1H1Fp1Us1_1
HT704B1-S1H3Fp1U1
HT704B1-S1H3Fp1U17
HT704B1-S1H3Fp1U26
HT704B1-S1H3Fp1U33
HT704B1-S1H3Fp1U41
HT704B1-S1H3Fp1U50
1581620AU1
1654977AU1
HT727B1-S1H4Fp1U1
1661918aU1
1607059U1
HT944B1-S2H2bFpU1
SP048Z1-Fp1C27U2
SP051Z1-Fp1F1U2
SP050Z1-Fp1A1U2""".split('\n')

In [70]:
for sid in sids:
    if sid in meta.index:
        print(meta.loc[sid, 'person'].lower())
    else:
        print('a')

a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
xiang
xiang
a
xiang
a
xiang
xiang
a
a
houston
houston
houston
houston
houston
houston
xiang
xiang
xiang
houston
houston
houston
houston
houston
houston
xiang
xiang
xiang
houston
houston
houston
a
a
xiangwei
xiangwei
houston
houston
houston
houston
houston
a
houston
houston
houston
houston
houston
houston
houston
xiangwei
xiangwei
xiangwei
xiangwei
xiangwei
xiangwei
a
a
a

In [73]:
meta = section_meta = pd.read_csv(StringIO("""section_id	dtype	person
SP003Z1-Fp1Us1_1	xenium	houston
SP017Z1-Fp1B27Us1_17	xenium	houston
SP017Z1-Fp1B27Us1_2	xenium	houston
SP017Z1-Fp1B27Us1_24	xenium	houston
SP017Z1-Fp1B27Us1_9	xenium	houston
SP003Z1-Fp1A15Us1_1	xenium	houston
SP004Z1-Fp1B17Us2_1	xenium	houston
SP005Z1-Fp1A25Us1_1	xenium	houston
SP006Z1-Fp1C8Us1_1	xenium	houston
SP008Z1-Fp1F15U1	xenium	houston
SP009Z1-Fp1B14U1	xenium	houston
SP012Z1-Fp1-A2U3	xenium	houston
SP015Z1-Fp1A1U3	xenium	houston
SP006Z1-Fp1C8Us2_1	xenium	houston
SP006Z1-Fp1C8Us2_12	xenium	houston
SP006Z1-Fp1C8Us2_18	xenium	houston
SP006Z1-Fp1C8Us2_20	xenium	houston
SP006Z1-Fp1C8Us2_5	xenium	houston
SP006Z1-Fp1C8Us2_7	xenium	houston
HT814Z1-S1H1Fp1Us1_3	xenium	xiang
HT817Z1-S1H1Fp1Us1_2	xenium	xiang
SP007Z1-Fp1A10Us2_1	xenium	houston
HT832Z1-S1H1Fp1U1	xenium	xiang
SP016Z1-Fp1B28U1	xenium	houston
HT849Z1-S1H2Fp1U1	xenium	xiang
HT852Z1-S1H1Fp1U1	xenium	xiang
SP011Z1-Fp1-A15U1	xenium	houston
SP014Z1-Fp1A29U1	xenium	houston
HT891Z1-S2H3Fp1U1	xenium	houston
HT891Z1-S2H3Fp1U21	xenium	houston
HT891Z1-S2H3Fp1U32	xenium	houston
HT891Z1-S2H3Fp1U44	xenium	houston
HT891Z1-S2H3Fp1U59	xenium	houston
HT891Z1-S2H3Fp1U69	xenium	houston
HT891Z1-S2H3Fp1U104	xenium	xiang
HT891Z1-S2H3Fp1U81	xenium	xiang
HT891Z1-S2H3Fp1U94	xenium	xiang
HT913Z1-S2H1Fp1U101	xenium	houston
HT913Z1-S2H1Fp1U33	xenium	houston
HT913Z1-S2H1Fp1U34	xenium	houston
HT913Z1-S2H1Fp1U35	xenium	houston
HT913Z1-S2H1Fp1U61	xenium	houston
HT913Z1-S2H1Fp1U81	xenium	houston
HT913Z1-S2H1Fp1U1	xenium	xiang
HT913Z1-S2H1Fp1U11	xenium	xiang
HT913Z1-S2H1Fp1U21	xenium	xiang
HT913Z1-S1H1Fp1U1	xenium	houston
HT913Z1-S1H1Fp1U11	xenium	houston
HT913Z1-S1H1Fp1U8	xenium	houston
SP048Z1-Fp1C27U1	xenium	houston
SP016Z1-Fp1B28U2	xenium	houston
HT832Z1-S1H1Fp1U2	xenium	xiangwei
HT1011Z1-S1H3Fp1U1	xenium	xiangwei
HT206B1-H2L1Us1_9	xenium	houston
HT206B1-H2L1Us1_17	xenium	houston
HT206B1-H2L1Us1_1	xenium	houston
HT206B1-H2L1Us1_24	xenium	houston
HT206B1-H2L1Us1_8	xenium	houston
HT206B1-H2L1Us1_15	xenium	houston
HT591B1-S1H1Fp1Us1_1	xenium	houston
HT704B1-S1H3Fp1U1	xenium	houston
HT704B1-S1H3Fp1U17	xenium	houston
HT704B1-S1H3Fp1U26	xenium	houston
HT704B1-S1H3Fp1U33	xenium	houston
HT704B1-S1H3Fp1U41	xenium	houston
HT704B1-S1H3Fp1U50	xenium	houston
1581620AU1	xenium	xiangwei
1654977AU1	xenium	xiangwei
HT727B1-S1H4Fp1U1	xenium	xiangwei
1661918aU1	xenium	xiangwei
1607059U1	xenium	xiangwei
HT944B1-S2H2bFpU1	xenium	xiangwei
SP048Z1-Fp1C27U2	xenium	houston
SP051Z1-Fp1F1U2	xenium	houston
SP050Z1-Fp1A1U2	xenium	houston
SP012Z1-Fp1A2-Ux	cosmx	gaurav
SP012Z1-Fp1A15-Ux	cosmx	gaurav
SP005Z1-Fp1A25-Ux	cosmx	gaurav
HT913Z1-S1H1Fp1	cosmx	gaurav
HT891Z1-S2H1Fp1	cosmx	gaurav
HT891Z1-S2H4Fp1	cosmx	gaurav
HT891Z1-S2H3FP1U57	cosmx	gaurav
HT891Z1-S2H3FP1U60	cosmx	gaurav
HT938Z1-S1H1FP1U1	cosmx	gaurav
HT997Z1-S1H1FP1U1	cosmx	gaurav
HT935Z1-S1H1FP1U2	cosmx	gaurav
HT206B1-H2L1U23_1	cosmx	gaurav
HT704B1-S1H3Fp1_U14	cosmx	gaurav
HT704B1-S1H3Fp1_U22	cosmx	gaurav
HT704B1-S1H3Fp1_U47	cosmx	gaurav
HT704B1-S1H3Fp1_U56	cosmx	gaurav
HT891Z1-S2H3Fp1U2	visiumhd	houston
HT891Z1-S2H3Fp1U33	visiumhd	houston
HT935Z1-S1H1Fp1U1	visiumhd	xiangwei
HT704B1-S1H3Fp1U2	visiumhd	xiang
HT704B1-S1H3Fp1U51	visiumhd	xiang
HT935Z1-S1H1Fp1U2	visiumhd	xiang
HT727B1-S1H4Fp1U1	visiumhd	xiang
HT206B1-S1Fc1U1Z1B1	visium 	siqi
HT206B1-S1Fc1U2Z1B1	visium 	siqi
HT206B1-S1Fc1U3Z1B1	visium 	siqi
HT206B1-S1Fc1U4Z1B1	visium 	siqi
HT206B1-S1Fc1U5Z1B1	visium 	siqi
HT297B1-S1H1Fc2U1Z1Bs1	visium 	siqi
HT308B1-S1H1Fc2U1Z1Bs1	visium 	siqi
HT308B1-S1H5Fc2U1Z1Bs1	visium 	siqi
HT308B1-S1H4Fc2U1Z1Bs1	visium 	siqi
HT323B1-S1H1Fc2U1Z1Bs1	visium 	siqi
HT339B1-S1H3Fc2U1Z1Bs1	visium 	siqi
HT339B1-S1H3Fc2U2Bs2	visium 	siqi
HT397B1-S1H3Fs1U1Bp1	visium 	siqi
HT397B1-S1H2Fs4U1Bp1	visium 	siqi
HT397B1-S1H3A1U1Bp1	visium 	siqi
HT397B1-S1H3A1U21Bp1	visium 	siqi
HT397B1-S1H3A1U41Bp1	visium 	siqi
HT397B1-S1H3A1U61Bp1	visium 	siqi
HT425B1-S1H2Fs1U2Bp1	visium 	andrew s
HT480B1-S1H1Fs1U1Bp1	visium 	siqi
HT480B1-S1H3Fs1U1Bp1	visium 	siqi
HT480B1-S1H1Fs1U2Bp1	visium 	andrew s
HT486B1-S1H1Fs1U1Bp1	visium 	siqi
HT486B1-S1H1Fs1U2Bp1	visium 	andrew s
SP017Z1-Fp1B27Us1_1Bp1	visium 	siqi
SP017Z1-Fp1B27Us1_16Bp1	visium 	siqi
SP060Z1-Fp1U1Bp1	visium 	siqi
SP008Z1-Fp1F15U1Bp1	visium 	siqi
HT206B1-U2	codex	siqi
HT206B1-U5	codex	siqi
HT206B1-U10	codex	siqi
HT206B1-U13	codex	siqi
HT206B1-U18	codex	siqi
HT206B1-U21	codex	siqi
HT339B2-H1-U2	codex	andrew s
HT397B1-U2	codex	andrew s
HT397B1-U12	codex	andrew s
HT397B1-U22	codex	andrew s
HT397B1-U31	codex	andrew s
HT565B1-H2-U2	codex	andrew s
HT704B1-U11	codex	faria
HT704B1-U19	codex	faria
HT704B1-U27	codex	faria
HT704B1-U35	codex	faria
HT704B1-U43	codex	faria
HT704B1-U53	codex	faria
HT704B1-U60	codex	faria
HT704B1-U68	codex	faria
HT704B1-U76	codex	faria
HT704B1-U82	codex	faria
HT704B1-U85	codex	faria
HT704B1-U91	codex	faria
HT891Z1-U14	codex	prostate
HT891Z1-U32	codex	xiang
HT891Z1-U40	codex	xiang
HT891Z1-U41	codex	xiang
HT891Z1-U43	codex	xiang
HT891Z1-U45	codex	xiang
HT891Z1-U46	codex	xiang
HT891Z1-U58	codex	xiang
HT891Z1-U79	codex	faria
HT891Z1-U93	codex	faria
HT891Z1-U103	codex	faria
HT891Z1-U108	codex	faria
HT891Z1-U109	codex	faria
HT891Z1-U110	codex	faria
HT891Z1-U111	codex	faria
HT891Z1-U113	codex	faria
HT913Z1-U2	codex	faria
HT913Z1-U12	codex	faria
HT913Z1-U22	codex	faria
HT913Z1-U41	codex	faria
HT913Z1-U51	codex	faria
HT913Z1-U52	codex	faria
HT913Z1-U53	codex	faria
HT913Z1-U54	codex	faria
HT913Z1-U62	codex	faria
HT913Z1-U71	codex	faria
HT913Z1-U82	codex	faria
HT913Z1-U91	codex	faria
HT913Z1-U102	codex	faria
HT913Z1-U111	codex	faria
HT913Z1-U121	codex	faria
HT913Z1-U125	codex	faria
SP006Z1-C8-U8	codex	xiang
SP006Z1-C8-U14	codex	xiang
SP006Z1-C8-U19	codex	xiang
SP006Z1-C8-U21	codex	xiang
SP006Z1-C8-U23	codex	xiang
SP006Z1-C8-U24	codex	xiang
SP017Z1-U3	codex	xiang
SP017Z1-U10	codex	xiang
SP017Z1-U18	codex	xiang
SP017Z1-U25	codex	xiang
HT323B1-H1A4	codex	siqi
HT110B1-S1H4	codex	siqi"""), sep='\t', header=None)
meta.columns = ['sid', 'dtype', 'person']

In [74]:
meta

                      sid   dtype   person
0              section_id   dtype   person
1        SP003Z1-Fp1Us1_1  xenium  houston
2    SP017Z1-Fp1B27Us1_17  xenium  houston
3     SP017Z1-Fp1B27Us1_2  xenium  houston
4    SP017Z1-Fp1B27Us1_24  xenium  houston
..                    ...     ...      ...
190           SP017Z1-U10   codex    xiang
191           SP017Z1-U18   codex    xiang
192           SP017Z1-U25   codex    xiang
193          HT323B1-H1A4   codex     siqi
194          HT110B1-S1H4   codex     siqi

[195 rows x 3 columns]

In [75]:
meta.groupby(['dtype', 'person']).count()

                   sid
dtype    person
codex    andrew s    6
         faria      36
         prostate    1
         siqi        8
         xiang      17
cosmx    gaurav     16
dtype    person      1
visium   andrew s    3
         siqi       25
visiumhd houston     2
         xiang       4
         xiangwei    1
xenium   houston    56
         xiang      11
         xiangwei    8

In [78]:
meta.groupby(['person']).count().sort_values('sid', ascending=False)

          sid  dtype
person
houston    58     58
faria      36     36
siqi       33     33
xiang      32     32
gaurav     16     16
andrew s    9      9
xiangwei    9      9
person      1      1
prostate    1      1

In [79]:
# panels
pieces = """8P9U3X_hMulti
hMulti
8P9U3X_hMulti
hMulti
8P9U3X_hMulti
hMulti
hMulti
J9HB8Q_hMulti
J9HB8Q_hMulti
J9HB8Q_hMulti
J9HB8Q_hMulti
J9HB8Q_hMulti
J9HB8Q_hMulti
HMTC / DHYHMW
8UT8B9_hMulti
8UT8B9_hMulti
8UT8B9_hMulti
HMTC / DHYHMW
8UT8B9_hMulti
8UT8B9_hMulti
TQDHMX_hMulti
TQDHMX_hMulti
TQDHMX_hMulti
TQDHMX_hMulti
TQDHMX_hMulti
TQDHMX_hMulti
J9HB8Q_hMulti
J9HB8Q_hMulti
J9HB8Q_hMulti
hMulti_v2
hMulti_v2
hMulti_v2
J9HB8Q_hMulti
J9HB8Q_hMulti
J9HB8Q_hMulti
J9HB8Q_hMulti
J9HB8Q_hMulti
J9HB8Q_hMulti
J9HB8Q_hMulti
J9HB8Q_hMulti
J9HB8Q_hMulti
HMTC / DHYHMW
HMTC / DHYHMW
8P9U3X_hMulti
8P9U3X_hMulti
8P9U3X_hMulti
8P9U3X_hMulti
8P9U3X_hMulti
8P9U3X_hMulti
8P9U3X_hMulti
8P9U3X_hMulti
8P9U3X_hMulti
8P9U3X_hMulti
8UT8B9_hMulti
8P9U3X_hMulti
8P9U3X_hMulti
8UT8B9_hMulti
8P9U3X_hMulti
8UT8B9_hMulti
8P9U3X_hMulti
8UT8B9_hMulti
8UT8B9_hMulti
hMulti
hMulti
hMulti
hMulti
J9HB8Q_hMulti
J9HB8Q_hMulti
J9HB8Q_hMulti
J9HB8Q_hMulti
HMTC / DHYHMW
HMTC / DHYHMW
HMTC / DHYHMW
HMTC / DHYHMW""".split('\n')
sorted(set(pieces))

['8P9U3X_hMulti',
 '8UT8B9_hMulti',
 'HMTC / DHYHMW',
 'J9HB8Q_hMulti',
 'TQDHMX_hMulti',
 'hMulti',
 'hMulti_v2']

In [2]:
df = pd.read_csv(StringIO("""case	section_id	z_depth	cohort	disease	channel_0	channel_1	channel_2	channel_3	channel_4	channel_5	channel_6	channel_7	channel_8	channel_9	channel_10	channel_11	channel_12	channel_13	channel_14	channel_15	channel_16	channel_17	channel_18	channel_19	channel_20	channel_21	channel_22	channel_23	channel_24	channel_25	channel_26	channel_27	channel_28	channel_29	channel_30	channel_31	channel_32	channel_33	channel_34	channel_35	channel_36	channel_37
HT206B1	HT206B1-U2	15	3d	breast	DAPI	Granzyme B	Keratin 5	PLAT/tPA (D)	GLUT1-(D)	CD4 (D)	SLC39A6 (D)	TCF-1	BCA1 (D)	CD68	CD39	FOXP3	CD163	PD-1	MLPH (D)	CD8	HER2 (D)	GATA3 (D)	cKIT (D)	Pan-Cytokeratin	HIF1a	Podoplanin (D)	CD20	HLA-DR	CK14 (D)	TFF1 (D)	MGP (D)	Ki67	Vimentin	CD31	E-cadherin	SMA (D)	cd11b	PR (D)	CD45 (D)	ER	COX6C (D)	
HT206B1	HT206B1-U5	20	3d	breast	DAPI	Granzyme B	Keratin 5	PLAT/tPA (D)	CTLA4 (D)	CD4 (D)	SLC39A6 (D)	TCF-1	BCA1 (D)	CD68	CD39	FOXP3	CD163	PD-1	MLPH	CD8	HER2 (D)	GLUT1 (D)	ckit-(D)	Pan-Cytokeratin	HIF1a	Podoplanin (D)	CD20	HLA-DR	CK14 (D)	TFF1 (D)	MGP (D)	Ki67	Vimentin	CD3e	E-cadherin	SMA (D)	cd11b	PR (D)	CD45 (D)	CD31	GATA3 (D)	COX6C (D)
HT206B1	HT206B1-U10	50	3d	breast	DAPI	Granzyme B	Keratin 5	PLAT/tPA (D)	GLUT1-(D)	CD4 (D)	SLC39A6 (D)	TCF-1	BCA1 (D)	CD68	CD39	FOXP3	CD163	PD-1	MLPH (D)	CD8	HER2 (D)	GATA3 (D)	cKIT (D)	Pan-Cytokeratin	HIF1a	Podoplanin (D)	CD20	HLA-DR	CK14 (D)	TFF1 (D)	MGP (D)	Ki67	Vimentin	CD31	E-cadherin	SMA (D)	cd11b	PR (D)	CD45 (D)	ER	COX6C (D)	
HT206B1	HT206B1-U13	65	3d	breast	DAPI	Granzyme B	Keratin 5	PLAT/tPA (D)	CTLA4 (D)	CD4 (D)	SLC39A6 (D)	TCF-1	BCA1 (D)	CD68	CD39	FOXP3	CD163	PD-1	MLPH	CD8	HER2 (D)	GLUT1 (D)	ckit-(D)	Pan-Cytokeratin	HIF1a	Podoplanin (D)	CD20	HLA-DR	CK14 (D)	TFF1 (D)	MGP (D)	Ki67	Vimentin	CD3e	E-cadherin	SMA (D)	cd11b	PR (D)	CD45 (D)	CD31	GATA3 (D)	COX6C (D)
HT206B1	HT206B1-U18	90	3d	breast	DAPI	Granzyme B	Keratin 5	PLAT/tPA (D)	GLUT1-(D)	CD4 (D)	SLC39A6 (D)	TCF-1	BCA1 (D)	CD68	CD39	FOXP3	CD163	PD-1	MLPH (D)	CD8	HER2 (D)	GATA3 (D)	cKIT (D)	Pan-Cytokeratin	HIF1a	Podoplanin (D)	CD20	HLA-DR	CK14 (D)	TFF1 (D)	MGP (D)	Ki67	Vimentin	CD31	E-cadherin	SMA (D)	cd11b	PR (D)	CD45 (D)	ER	COX6C (D)	
HT206B1	HT206B1-U21	105	3d	breast	DAPI	Granzyme B	Keratin 5	PLAT/tPA (D)	CTLA4 (D)	CD4 (D)	SLC39A6 (D)	TCF-1	BCA1 (D)	CD68	CD39	FOXP3	CD163	PD-1	MLPH	CD8	HER2 (D)	GLUT1 (D)	ckit-(D)	Pan-Cytokeratin	HIF1a	Podoplanin (D)	CD20	HLA-DR	CK14 (D)	TFF1 (D)	MGP (D)	Ki67	Vimentin	CD3e	E-cadherin	SMA (D)	cd11b	PR (D)	CD45 (D)	CD31	GATA3 (D)	COX6C (D)
HT339B2	HT339B2-H1-U2	5	3d	breast	DAPI	CD8	Her2 (D)	GATA3 (D)	cKIT-(D)	Pan-Cytokeratin	GLUT1-(D)	Podoplanin	CD68 (D)	HLA-DR	Keratin 14	TFF1 (D)	MGP-(D)	a-Amylase	SMA-(D)	CD3e	Ki67	Vimentin-(D)	CD11b (D)	PR-(D)	Bap1 (D)	CD45 (D)	ER	CD31	COX6c (D)	CK19	CK17-(D)	PLAT/tPA (D)	CTLA4	Hep-Par-1 (D)	CD4	SLC39A6	Keratin 5					
HT397B1	HT397B1-U2	5	3d	breast	DAPI	CD8	Her2 (D)	GATA3 (D)	cKIT-(D)	Pan-Cytokeratin	GLUT1-(D)	Podoplanin	CD68 (D)	HLA-DR	Keratin 14	FoxP3	MGP-(D)	CD20-(D)	SMA-(D)	Ki67	Vimentin-(D)	PR-(D)	Bap1 (D)	CD45 (D)	ER	CD31	COX6c (D)	CK19	PLAT/tPA (D)													
HT397B1	HT397B1-U12	55	3d	breast	DAPI	CD8	Her2 (D)	GATA3 (D)	cKIT-(D)	Pan-Cytokeratin	GLUT1-(D)	Podoplanin	CD68 (D)	HLA-DR	Keratin 14	FoxP3	MGP-(D)	CD20-(D)	SMA-(D)	Ki67	Vimentin-(D)	PR-(D)	Bap1 (D)	CD45 (D)	ER	CD31	COX6c (D)	CK19	PLAT/tPA (D)													
HT397B1	HT397B1-U22	105	3d	breast	DAPI	CD8	Her2 (D)	GATA3 (D)	cKIT-(D)	Pan-Cytokeratin	GLUT1-(D)	Podoplanin	CD68 (D)	HLA-DR	Keratin 14	FoxP3	MGP-(D)	E-cadherin	SMA-(D)	CD3e	Ki67	Vimentin-(D)	CD11b	PR-(D)	Bap1 (D)	CD45 (D)	ER	CD31	COX6c (D)	CK19	PLAT/tPA (D)											
HT397B1	HT397B1-U31	150	3d	breast	DAPI	CD8	Her2 (D)	GATA3 (D)	cKIT-(D)	Pan-Cytokeratin	GLUT1-(D)	Podoplanin	CD68 (D)	HLA-DR	Keratin 14	FoxP3	MGP-(D)	SMA-(D)	CD3e	Ki67	Vimentin-(D)	PR-(D)	Bap1 (D)	CD45 (D)	ER	CD31	COX6c (D)	CK19	PLAT/tPA (D)													
HT565B1	HT565B1-H2-U2	5	3d	breast	DAPI	CD8	Her2 (D)	GATA3 (D)	cKIT-(D)	Pan-Cytokeratin	GLUT1-(D)	Podoplanin	CD68 (D)	HLA-DR	Keratin 14	TFF1 (D)	MGP-(D)	a-Amylase	SMA-(D)	CD3e	Ki67	Vimentin-(D)	CD11b (D)	PR-(D)	Bap1 (D)	CD45 (D)	ER	CD31	COX6c (D)	CK19	CK17-(D)	PLAT/tPA (D)	CTLA4	Hep-Par-1 (D)	CD4	SLC39A6	Keratin 5					
HT704B1	HT704B1-U11	50	3d	breast	DAPI	Granzyme B	Keratin 5	PLAT/tPA (D)	CTLA4 (D)	CD31	CD4 (D)	SLC39A6 (D)	TCF-1	BCA1	CD68	CD39	FOXP3	CD163	PD-1	MLPH	CD8	HER2 (D)	GLUT1 (D)	ckit-(D)	Pan-Cytokeratin	HIF1a	Podoplanin (D)	CD20	HLA-DR	CK14 (D)	TFF1 (D)	MGP (D)	Ki67	Vimentin	CD3e	E-cadherin	SMA (D)	cd11b	PR (D)	CD45 (D)	GATA3	COX6C (D)
HT704B1	HT704B1-U19	90	3d	breast	DAPI	Granzyme B	Keratin 5	PLAT/tPA (D)	CTLA4 (D)	CD31	CD4 (D)	SLC39A6 (D)	TCF-1	BCA1	CD68	CD39	FOXP3	CD163	PD-1	MLPH	CD8	HER2 (D)	GLUT1 (D)	ckit-(D)	Pan-Cytokeratin	HIF1a	Podoplanin (D)	CD20	HLA-DR	CK14 (D)	TFF1 (D)	MGP (D)	Ki67	Vimentin	CD3e	E-cadherin	SMA (D)	cd11b	PR (D)	CD45 (D)	GATA3	COX6C (D)
HT704B1	HT704B1-U27	130	3d	breast	DAPI	Granzyme B	Keratin 5	PLAT/tPA (D)	CTLA4 (D)	CD31	CD4 (D)	SLC39A6 (D)	TCF-1	BCA1	CD68	CD39	FOXP3	CD163	PD-1	MLPH	CD8	HER2 (D)	GLUT1 (D)	ckit-(D)	Pan-Cytokeratin	HIF1a	Podoplanin (D)	CD20	HLA-DR	CK14 (D)	TFF1 (D)	MGP (D)	Ki67	Vimentin	CD3e	E-cadherin	SMA (D)	cd11b	PR (D)	CD45 (D)	GATA3	COX6C (D)
HT704B1	HT704B1-U35	170	3d	breast	DAPI	Granzyme B	Keratin 5	PLAT/tPA (D)	CTLA4 (D)	CD31	CD4 (D)	SLC39A6 (D)	TCF-1	BCA1	CD68	CD39	FOXP3	CD163	PD-1	MLPH	CD8	HER2 (D)	GLUT1 (D)	ckit-(D)	Pan-Cytokeratin	HIF1a	Podoplanin (D)	CD20	HLA-DR	CK14 (D)	TFF1 (D)	MGP (D)	Ki67	Vimentin	CD3e	E-cadherin	SMA (D)	cd11b	PR (D)	CD45 (D)	GATA3	COX6C (D)
HT704B1	HT704B1-U43	210	3d	breast	DAPI	Granzyme B	Keratin 5	PLAT/tPA (D)	CTLA4 (D)	CD31	CD4 (D)	SLC39A6 (D)	TCF-1	BCA1	CD68	CD39	FOXP3	CD163	PD-1	MLPH	CD8	HER2 (D)	GLUT1 (D)	ckit-(D)	Pan-Cytokeratin	HIF1a	Podoplanin (D)	CD20	HLA-DR	CK14 (D)	TFF1 (D)	MGP (D)	Ki67	Vimentin	CD3e	E-cadherin	SMA (D)	cd11b	PR (D)	CD45 (D)	GATA3	COX6C (D)
HT704B1	HT704B1-U53	260	3d	breast	DAPI	Granzyme B	Keratin 5	PLAT/tPA (D)	CTLA4 (D)	CD31	CD4 (D)	SLC39A6 (D)	TCF-1	BCA1	CD68	CD39	FOXP3	CD163	PD-1	MLPH	CD8	HER2 (D)	GLUT1 (D)	ckit-(D)	Pan-Cytokeratin	HIF1a	Podoplanin (D)	CD20	HLA-DR	CK14 (D)	TFF1 (D)	MGP (D)	Ki67	Vimentin	CD3e	E-cadherin	SMA (D)	cd11b	PR (D)	CD45 (D)	GATA3	COX6C (D)
HT704B1	HT704B1-U60	295	3d	breast	DAPI	Granzyme B	Keratin 5	PLAT/tPA (D)	CTLA4 (D)	CD31	CD4 (D)	SLC39A6 (D)	TCF-1	BCA1	CD68	CD39	FOXP3	CD163	PD-1	MLPH	CD8	HER2 (D)	GLUT1 (D)	ckit-(D)	Pan-Cytokeratin	HIF1a	Podoplanin (D)	CD20	HLA-DR	CK14 (D)	TFF1 (D)	MGP (D)	Ki67	Vimentin	CD3e	E-cadherin	SMA (D)	cd11b	PR (D)	CD45 (D)	GATA3	COX6C (D)
HT704B1	HT704B1-U68	335	3d	breast	DAPI	Granzyme B	Keratin 5	PLAT/tPA (D)	CTLA4 (D)	CD31	CD4 (D)	SLC39A6 (D)	TCF-1	BCA1	CD68	CD39	FOXP3	CD163	PD-1	MLPH	CD8	HER2 (D)	GLUT1 (D)	ckit-(D)	Pan-Cytokeratin	HIF1a	Podoplanin (D)	CD20	HLA-DR	CK14 (D)	TFF1 (D)	MGP (D)	Ki67	Vimentin	CD3e	E-cadherin	SMA (D)	cd11b	PR (D)	CD45 (D)	GATA3	COX6C (D)
HT704B1	HT704B1-U76	375	3d	breast	DAPI	Granzyme B	Keratin 5	PLAT/tPA (D)	CTLA4 (D)	CD31	CD4 (D)	SLC39A6 (D)	TCF-1	BCA1	CD68	CD39	FOXP3	CD163	PD-1	MLPH	CD8	HER2 (D)	GLUT1 (D)	ckit-(D)	Pan-Cytokeratin	HIF1a	Podoplanin (D)	CD20	HLA-DR	CK14 (D)	TFF1 (D)	MGP (D)	Ki67	Vimentin	CD3e	E-cadherin	SMA (D)	cd11b	PR (D)	CD45 (D)	GATA3	COX6C (D)
HT704B1	HT704B1-U82	405	3d	breast	DAPI	Granzyme B	Keratin 5	PLAT/tPA (D)	CTLA4 (D)	CD31	CD4 (D)	SLC39A6 (D)	TCF-1	BCA1	CD68	CD39	FOXP3	CD163	PD-1	MLPH	CD8	HER2 (D)	GLUT1 (D)	ckit-(D)	Pan-Cytokeratin	HIF1a	Podoplanin (D)	CD20	HLA-DR	CK14 (D)	TFF1 (D)	MGP (D)	Ki67	Vimentin	CD3e	E-cadherin	SMA (D)	cd11b	PR (D)	CD45 (D)	GATA3	COX6C (D)
HT704B1	HT704B1-U85	420	3d	breast	DAPI	Granzyme B	Keratin 5	PLAT/tPA (D)	CTLA4 (D)	CD31	CD4 (D)	SLC39A6 (D)	TCF-1	BCA1	CD68	CD39	FOXP3	CD163	PD-1	MLPH	CD8	HER2 (D)	GLUT1 (D)	ckit-(D)	Pan-Cytokeratin	HIF1a	Podoplanin (D)	CD20	HLA-DR	CK14 (D)	TFF1 (D)	MGP (D)	Ki67	Vimentin	CD3e	E-cadherin	SMA (D)	cd11b	PR (D)	CD45 (D)	GATA3	COX6C (D)
HT704B1	HT704B1-U91	450	3d	breast	DAPI	Granzyme B	Keratin 5	PLAT/tPA (D)	CTLA4 (D)	CD31	CD4 (D)	SLC39A6 (D)	TCF-1	BCA1	CD68	CD39	FOXP3	CD163	PD-1	MLPH	CD8	HER2 (D)	GLUT1 (D)	ckit-(D)	Pan-Cytokeratin	HIF1a	Podoplanin (D)	CD20	HLA-DR	CK14 (D)	TFF1 (D)	MGP (D)	Ki67	Vimentin	CD3e	E-cadherin	SMA (D)	cd11b	PR (D)	CD45 (D)	GATA3	COX6C (D)
HT891Z1	HT891Z1-U14	65	3d	prostate	DAPI	CK14	LYVE1	CD4	CK5	STEAP4	CD68	E-Cadherin	SMA (D)	CD45(D)	p63	Pan-Cytokeratin	HLA-DR	Podoplanin	Vimentin	CD3e	CD8	CK7	CD44	Foxp3	CD20	Ki67	AR	AMACR	CD31													
HT891Z1	HT891Z1-U32	155	3d	prostate	DAPI	CK14	LYVE1	CD4	CK5	STEAP4	CD68	E-Cadherin	SMA (D)	CD45(D)	p63	Pan-Cytokeratin	HLA-DR	Podoplanin	Vimentin	CD3e	CD8	CK7	CD44	Foxp3	CD20	Ki67	AR	AMACR	CD31													
HT891Z1	HT891Z1-U40	195	3d	prostate	DAPI	CK14	LYVE1	CD4	CK5	STEAP4	CD68	E-Cadherin	SMA (D)	CD45(D)	p63	Pan-Cytokeratin	HLA-DR	Podoplanin	Vimentin	CD3e	CD8	CK7	CD44	Foxp3	CD20	Ki67	AR	AMACR	CD31													
HT891Z1	HT891Z1-U41	200	3d	prostate	DAPI	CK14	LYVE1	CD4	CK5	STEAP4	CD68	E-Cadherin	SMA (D)	CD45(D)	p63	Pan-Cytokeratin	HLA-DR	Podoplanin	Vimentin	CD3e	CD8	CK7	CD44	Foxp3	CD20	Ki67	AR	AMACR	CD31													
HT891Z1	HT891Z1-U43	210	3d	prostate	DAPI	CK14	LYVE1	CD4	CK5	STEAP4	CD68	E-Cadherin	SMA (D)	CD45(D)	p63	Pan-Cytokeratin	HLA-DR	Podoplanin	Vimentin	CD3e	CD8	CK7	CD44	Foxp3	CD20	Ki67	AR	AMACR	CD31													
HT891Z1	HT891Z1-U45	220	3d	prostate	DAPI	CK14	LYVE1	CD4	CK5	STEAP4	CD68	E-Cadherin	SMA (D)	CD45(D)	p63	Pan-Cytokeratin	HLA-DR	Podoplanin	Vimentin	CD3e	CD8	CK7	CD44	Foxp3	CD20	Ki67	AR	AMACR	CD31													
HT891Z1	HT891Z1-U46	225	3d	prostate	DAPI	CK14	LYVE1	CD4	CK5	STEAP4	CD68	E-Cadherin	SMA (D)	CD45(D)	p63	Pan-Cytokeratin	HLA-DR	Podoplanin	Vimentin	CD3e	CD8	CK7	CD44	Foxp3	CD20	Ki67	AR	AMACR	CD31													
HT891Z1	HT891Z1-U58	285	3d	prostate	DAPI	CK14	LYVE1	CD4	CK5	STEAP4	CD68	E-Cadherin	SMA (D)	CD45(D)	p63	Pan-Cytokeratin	HLA-DR	Podoplanin	Vimentin	CD3e	CD8	CK7	CD44	Foxp3	CD20	Ki67	AR	AMACR	CD31													
HT891Z1	HT891Z1-U79	390	3d	prostate	DAPI	CK14	LYVE1	CD4	CK5	STEAP4	CD68	E-Cadherin	SMA (D)	CD45(D)	p63	Pan-Cytokeratin	HLA-DR	Podoplanin	Vimentin	CD3e	CD8	CK7	CD44	Foxp3	CD20	Ki67	AR	AMACR	CD31													
HT891Z1	HT891Z1-U93	460	3d	prostate	DAPI	CK14	LYVE1	CD4	CK5	STEAP4	CD68	E-Cadherin	SMA (D)	CD45(D)	p63	Pan-Cytokeratin	HLA-DR	Podoplanin	Vimentin	CD3e	CD8	CK7	CD44	Foxp3	CD20	Ki67	AR	AMACR	CD31													
HT891Z1	HT891Z1-U103	510	3d	prostate	DAPI	CK14	LYVE1	CD4	CK5	STEAP4	CD68	E-Cadherin	SMA (D)	CD45(D)	p63	Pan-Cytokeratin	HLA-DR	Podoplanin	Vimentin	CD3e	CD8	CK7	CD44	Foxp3	CD20	Ki67	AR	AMACR	CD31													
HT891Z1	HT891Z1-U108	535	3d	prostate	DAPI	CK14	LYVE1	CD4	CK5	STEAP4	CD68	E-Cadherin	SMA (D)	CD45(D)	p63	Pan-Cytokeratin	HLA-DR	Podoplanin	Vimentin	CD3e	CD8	CK7	CD44	Foxp3	CD20	Ki67	AR	AMACR	CD31													
HT891Z1	HT891Z1-U109	540	3d	prostate	DAPI	CK14	LYVE1	CD4	CK5	STEAP4	CD68	E-Cadherin	SMA (D)	CD45(D)	p63	Pan-Cytokeratin	HLA-DR	Podoplanin	Vimentin	CD3e	CD8	CK7	CD44	Foxp3	CD20	Ki67	AR	AMACR	CD31													
HT891Z1	HT891Z1-U110	545	3d	prostate	DAPI	CK14	LYVE1	CD4	CK5	STEAP4	CD68	E-Cadherin	SMA (D)	CD45(D)	p63	Pan-Cytokeratin	HLA-DR	Podoplanin	Vimentin	CD3e	CD8	CK7	CD44	Foxp3	CD20	Ki67	AR	AMACR	CD31													
HT891Z1	HT891Z1-U111	550	3d	prostate	DAPI	CK14	LYVE1	CD4	CK5	STEAP4	CD68	E-Cadherin	SMA (D)	CD45(D)	p63	Pan-Cytokeratin	HLA-DR	Podoplanin	Vimentin	CD3e	CD8	CK7	CD44	Foxp3	CD20	Ki67	AR	AMACR	CD31													
HT891Z1	HT891Z1-U113	560	3d	prostate	DAPI	CK14	LYVE1	CD4	CK5	STEAP4	CD68	E-Cadherin	SMA (D)	CD45(D)	p63	Pan-Cytokeratin	HLA-DR	Podoplanin	Vimentin	CD3e	CD8	CK7	CD44	Foxp3	CD20	Ki67	AR	AMACR	CD31													
HT913Z1	HT913Z1-U2	5	3d	prostate	DAPI	CK14	LYVE1	CD4	CK5	STEAP4	CD68	E-Cadherin	SMA (D)	CD45(D)	p63	Pan-Cytokeratin	HLA-DR	Podoplanin	Vimentin	CD3e	CD8	CK7	CD44	Foxp3	CD20	Ki67	AR	AMACR	CD31													
HT913Z1	HT913Z1-U12	55	3d	prostate	DAPI	CK14	LYVE1	CD4	CK5	STEAP4	CD68	E-Cadherin	SMA (D)	CD45(D)	p63	Pan-Cytokeratin	HLA-DR	Podoplanin	Vimentin	CD3e	CD8	CK7	CD44	Foxp3	CD20	Ki67	AR	AMACR	CD31													
HT913Z1	HT913Z1-U22	105	3d	prostate	DAPI	CK14	LYVE1	CD4	CK5	STEAP4	CD68	E-Cadherin	SMA (D)	CD45(D)	p63	Pan-Cytokeratin	HLA-DR	Podoplanin	Vimentin	CD3e	CD8	CK7	CD44	Foxp3	CD20	Ki67	AR	AMACR	CD31													
HT913Z1	HT913Z1-U41	200	3d	prostate	DAPI	CK14	LYVE1	CD4	CK5	STEAP4	CD68	E-Cadherin	SMA (D)	CD45(D)	p63	Pan-Cytokeratin	HLA-DR	Podoplanin	Vimentin	CD3e	CD8	CK7	CD44	Foxp3	CD20	Ki67	AR	AMACR	CD31													
HT913Z1	HT913Z1-U51	250	3d	prostate	DAPI	CK14	LYVE1	CD4	CK5	STEAP4	CD68	E-Cadherin	SMA (D)	CD45(D)	p63	Pan-Cytokeratin	HLA-DR	Podoplanin	Vimentin	CD3e	CD8	CK7	CD44	Foxp3	CD20	Ki67	AR	AMACR	CD31													
HT913Z1	HT913Z1-U52	255	3d	prostate	DAPI	CK14	LYVE1	CD4	CK5	STEAP4	CD68	E-Cadherin	SMA (D)	CD45(D)	p63	Pan-Cytokeratin	HLA-DR	Podoplanin	Vimentin	CD3e	CD8	CK7	CD44	Foxp3	CD20	Ki67	AR	AMACR	CD31													
HT913Z1	HT913Z1-U53	260	3d	prostate	DAPI	CK14	LYVE1	CD4	CK5	STEAP4	CD68	E-Cadherin	SMA (D)	CD45(D)	p63	Pan-Cytokeratin	HLA-DR	Podoplanin	Vimentin	CD3e	CD8	CK7	CD44	Foxp3	CD20	Ki67	AR	AMACR	CD31													
HT913Z1	HT913Z1-U54	265	3d	prostate	DAPI	CK14	LYVE1	CD4	CK5	STEAP4	CD68	E-Cadherin	SMA (D)	CD45(D)	p63	Pan-Cytokeratin	HLA-DR	Podoplanin	Vimentin	CD3e	CD8	CK7	CD44	Foxp3	CD20	Ki67	AR	AMACR	CD31													
HT913Z1	HT913Z1-U62	305	3d	prostate	DAPI	CK14	LYVE1	CD4	CK5	STEAP4	CD68	E-Cadherin	SMA (D)	CD45(D)	p63	Pan-Cytokeratin	HLA-DR	Podoplanin	Vimentin	CD3e	CD8	CK7	CD44	Foxp3	CD20	Ki67	AR	AMACR	CD31													
HT913Z1	HT913Z1-U71	350	3d	prostate	DAPI	CK14	LYVE1	CD4	CK5	STEAP4	CD68	E-Cadherin	SMA (D)	CD45(D)	p63	Pan-Cytokeratin	HLA-DR	Podoplanin	Vimentin	CD3e	CD8	CK7	CD44	Foxp3	CD20	Ki67	AR	AMACR	CD31													
HT913Z1	HT913Z1-U82	405	3d	prostate	DAPI	CK14	LYVE1	CD4	CK5	STEAP4	CD68	E-Cadherin	SMA (D)	CD45(D)	p63	Pan-Cytokeratin	HLA-DR	Podoplanin	Vimentin	CD3e	CD8	CK7	CD44	Foxp3	CD20	Ki67	AR	AMACR	CD31													
HT913Z1	HT913Z1-U91	450	3d	prostate	DAPI	CK14	LYVE1	CD4	CK5	STEAP4	CD68	E-Cadherin	SMA (D)	CD45(D)	p63	Pan-Cytokeratin	HLA-DR	Podoplanin	Vimentin	CD3e	CD8	CK7	CD44	Foxp3	CD20	Ki67	AR	AMACR	CD31													
HT913Z1	HT913Z1-U102	505	3d	prostate	DAPI	CK14	LYVE1	CD4	CK5	STEAP4	CD68	E-Cadherin	SMA (D)	CD45(D)	p63	Pan-Cytokeratin	HLA-DR	Podoplanin	Vimentin	CD3e	CD8	CK7	CD44	Foxp3	CD20	Ki67	AR	AMACR	CD31													
HT913Z1	HT913Z1-U111	550	3d	prostate	DAPI	CK14	LYVE1	CD4	CK5	STEAP4	CD68	E-Cadherin	SMA (D)	CD45(D)	p63	Pan-Cytokeratin	HLA-DR	Podoplanin	Vimentin	CD3e	CD8	CK7	CD44	Foxp3	CD20	Ki67	AR	AMACR	CD31													
HT913Z1	HT913Z1-U121	600	3d	prostate	DAPI	CK14	LYVE1	CD4	CK5	STEAP4	CD68	E-Cadherin	SMA (D)	CD45(D)	p63	Pan-Cytokeratin	HLA-DR	Podoplanin	Vimentin	CD3e	CD8	CK7	CD44	Foxp3	CD20	Ki67	AR	AMACR	CD31													
HT913Z1	HT913Z1-U125	620	3d	prostate	DAPI	CK14	LYVE1	CD4	CK5	STEAP4	CD68	E-Cadherin	SMA (D)	CD45(D)	p63	Pan-Cytokeratin	HLA-DR	Podoplanin	Vimentin	CD3e	CD8	CK7	CD44	Foxp3	CD20	Ki67	AR	AMACR	CD31													
SP006Z1	SP006Z1-C8-U8	35	3d	prostate	DAPI	CK14	LYVE1	CD4	CK5	STEAP4	CD68	E-Cadherin	SMA (D)	CD45(D)	p63	Pan-Cytokeratin	HLA-DR	Podoplanin	Vimentin	CD3e	CD8	CK7	CD31 (D)	CD20 (D)	CK8/18	Ki67	AR	AMACR														
SP006Z1	SP006Z1-C8-U14	65	3d	prostate	DAPI	CK14	LYVE1	CD4	CK5	STEAP4	CD68	E-Cadherin	SMA (D)	CD45(D)	p63	Pan-Cytokeratin	HLA-DR	Podoplanin	Vimentin	CD3e	CD8	CK7	CD31 (D)	CD20 (D)	CK8/18	Ki67	AR	AMACR														
SP006Z1	SP006Z1-C8-U19	90	3d	prostate	DAPI	CK14	LYVE1	CD4	CK5	STEAP4	CD68	E-Cadherin	SMA (D)	CD45(D)	p63	Pan-Cytokeratin	HLA-DR	Podoplanin	Vimentin	CD3e	CD8	CK7	CD31 (D)	CD20 (D)	CK8/18	Ki67	AR	AMACR														
SP006Z1	SP006Z1-C8-U21	100	3d	prostate	DAPI	CK14	LYVE1	CD4	CK5	STEAP4	CD68	E-Cadherin	SMA (D)	CD45(D)	p63	Pan-Cytokeratin	HLA-DR	Podoplanin	Vimentin	CD3e	CD8	CK7	CD31 (D)	CD20 (D)	CK8/18	Ki67	AR	AMACR														
SP006Z1	SP006Z1-C8-U23	110	3d	prostate	DAPI	CK14	LYVE1	CD4	CK5	STEAP4	CD68	E-Cadherin	SMA (D)	CD45(D)	p63	Pan-Cytokeratin	HLA-DR	Podoplanin	Vimentin	CD3e	CD8	CK7	CD31 (D)	CD20 (D)	CK8/18	Ki67	AR	AMACR														
SP006Z1	SP006Z1-C8-U24	115	3d	prostate	DAPI	CK14	LYVE1	CD4	CK5	STEAP4	CD68	E-Cadherin	SMA (D)	CD45(D)	p63	Pan-Cytokeratin	HLA-DR	Podoplanin	Vimentin	CD3e	CD8	CK7	CD31 (D)	CD20 (D)	CK8/18	Ki67	AR	AMACR														
SP017Z1	SP017Z1-U3	10	3d	prostate	DAPI	CK14	LYVE1	CD4	CK5	STEAP4	CD68	E-Cadherin	SMA (D)	CD45(D)	p63	Pan-Cytokeratin	HLA-DR	Podoplanin	Vimentin	CD3e	CD8	CK7	CD31 (D)	CD20 (D)	Foxp3	Ki67	AR	AMACR														
SP017Z1	SP017Z1-U10	45	3d	prostate	DAPI	CK14	LYVE1	CD4	CK5	STEAP4	CD68	E-Cadherin	SMA (D)	CD45(D)	p63	Pan-Cytokeratin	HLA-DR	Podoplanin	Vimentin	CD3e	CD8	CK7	CD31 (D)	CD20 (D)	Foxp3	Ki67	AR	AMACR														
SP017Z1	SP017Z1-U18	125	3d	prostate	DAPI	CK14	LYVE1	CD4	CK5	STEAP4	CD68	E-Cadherin	SMA (D)	CD45(D)	p63	Pan-Cytokeratin	HLA-DR	Podoplanin	Vimentin	CD3e	CD8	CK7	CD31 (D)	CD20 (D)	Foxp3	Ki67	AR	AMACR														
SP017Z1	SP017Z1-U25	160	3d	prostate	DAPI	CK14	LYVE1	CD4	CK5	STEAP4	CD68	E-Cadherin	SMA (D)	CD45(D)	p63	Pan-Cytokeratin	HLA-DR	Podoplanin	Vimentin	CD3e	CD8	CK7	CD31 (D)	CD20 (D)	Foxp3	Ki67	AR	AMACR														
HT323B1	HT323B1-H1A4		validation	breast	DAPI	CD31	E-cadherin	CD4	CD20	Ki67	CD68	Pan-CK	CD8	Histone H3 Pho	CD163	Podoplanin	CD3e	beta-integrin	HIF1a	GLUT1	GATA3	CD45RO	CD45RA	SMA	CK19	MGP	Vimentin	Maspin	Foxp3	CK17	MMP9	HLA-DR	CD36	CK14	CD11c	CD44						
HT110B1	HT110B1-S1H4		validation	breast	DAPI	CD8	CD138	CD4	cKIT-(D)	Pan-Cytokeratin	GLUT1-(D)	Podoplanin	Keratin 17	HLA-DR	GATA3-(D)	CD36-(D)	MGP-(D)	Keratin 14	SMA-(D)	CD68	CD20-(D)	Vimentin-(D)	CD3e	CD163	Ki67	PR-(D)	ER	P16-(D)	CK19	P21 (D)												"""), sep='\t')
df

,case,section_id,z_depth,cohort,disease,channel_0,channel_1,channel_2,channel_3,channel_4,...,channel_28,channel_29,channel_30,channel_31,channel_32,channel_33,channel_34,channel_35,channel_36,channel_37
0,HT206B1,HT206B1-U2,15.0,3d,breast,DAPI,Granzyme B,Keratin 5,PLAT/tPA (D),GLUT1-(D),...,Vimentin,CD31,E-cadherin,SMA (D),cd11b,PR (D),CD45 (D),ER,COX6C (D),NaN
1,HT206B1,HT206B1-U5,20.0,3d,breast,DAPI,Granzyme B,Keratin 5,PLAT/tPA (D),CTLA4 (D),...,Vimentin,CD3e,E-cadherin,SMA (D),cd11b,PR (D),CD45 (D),CD31,GATA3 (D),COX6C (D)
2,HT206B1,HT206B1-U10,50.0,3d,breast,DAPI,Granzyme B,Keratin 5,PLAT/tPA (D),GLUT1-(D),...,Vimentin,CD31,E-cadherin,SMA (D),cd11b,PR (D),CD45 (D),ER,COX6C (D),NaN
3,HT206B1,HT206B1-U13,65.0,3d,breast,DAPI,Granzyme B,Keratin 5,PLAT/tPA (D),CTLA4 (D),...,Vimentin,CD3e,E-cadherin,SMA (D),cd11b,PR (D),CD45 (D),CD31,GATA3 (D),COX6C (D)
4,HT206B1,HT206B1-U18,90.0,3d,breast,DAPI,Granzyme B,Keratin 5,PLAT/tPA (D),GLUT1-(D),...,Vimentin,CD31,E-cadherin,SMA (D),cd11b,PR (D),CD45 (D),ER,COX6C (D),NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63,SP017Z1,SP017Z1-U10,45.0,3d,prostate,DAPI,CK14,LYVE1,CD4,CK5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64,SP017Z1,SP017Z1-U18,125.0,3d,prostate,DAPI,CK14,LYVE1,CD4,CK5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65,SP017Z1,SP017Z1-U25,160.0,3d,prostate,DAPI,CK14,LYVE1,CD4,CK5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66,HT323B1,HT323B1-H1A4,NaN,validation,breast,DAPI,CD31,E-cadherin,CD4,CD20,...,CD36,CK14,CD11c,CD44,NaN,NaN,NaN,NaN,NaN,NaN
67,HT110B1,HT110B1-S1H4,NaN,validation,breast,DAPI,CD8,CD138,CD4,cKIT-(D),...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
import re
re.sub(r'^(.*)[ -]\(D\)', r'\1', 'BCA1 (D)')

'BCA1'

In [9]:
cols = sorted(set(df.iloc[:, 5:].values.flatten().astype(str)))
cols = sorted(set([re.sub(r'^(.*)[ -]\(D\)', r'\1', x) for x in cols]))
for x in cols:
    print(x)

AMACR
AR
BCA1
Bap1
CD11b
CD11c
CD138
CD163
CD20
CD31
CD36
CD39
CD3e
CD4
CD44
CD45
CD45(D)
CD45RA
CD45RO
CD68
CD8
CK14
CK17
CK19
CK5
CK7
CK8/18
COX6C
COX6c
CTLA4
DAPI
E-Cadherin
E-cadherin
ER
FOXP3
FoxP3
Foxp3
GATA3
GLUT1
Granzyme B
HER2
HIF1a
HLA-DR
Hep-Par-1
Her2
Histone H3 Pho
Keratin 14
Keratin 17
Keratin 5
Ki67
LYVE1
MGP
MLPH
MMP9
Maspin
P16
P21
PD-1
PLAT/tPA
PR
Pan-CK
Pan-Cytokeratin
Podoplanin
SLC39A6
SMA
STEAP4
TCF-1
TFF1
Vimentin
a-Amylase
beta-integrin
cKIT
cd11b
ckit
nan
p63